"""add bls sentinel system

Revision ID: 0adf07805582
Revises: 5efe1839af96
Create Date: 2025-11-19 10:11:34.933064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0adf07805582'
down_revision: Union[str, Sequence[str], None] = '5efe1839af96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_survey_freshness',
    sa.Column('survey_code', sa.String(length=5), nullable=False),
    sa.Column('last_bls_update_detected', sa.DateTime(), nullable=True),
    sa.Column('last_sentinel_check', sa.DateTime(), nullable=True),
    sa.Column('sentinels_changed', sa.Integer(), nullable=False),
    sa.Column('sentinels_total', sa.Integer(), nullable=False),
    sa.Column('needs_full_update', sa.Boolean(), nullable=False),
    sa.Column('last_full_update_started', sa.DateTime(), nullable=True),
    sa.Column('last_full_update_completed', sa.DateTime(), nullable=True),
    sa.Column('full_update_in_progress', sa.Boolean(), nullable=False),
    sa.Column('series_updated_count', sa.Integer(), nullable=False),
    sa.Column('series_total_count', sa.Integer(), nullable=False),
    sa.Column('bls_update_frequency_days', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_checks', sa.Integer(), nullable=False),
    sa.Column('total_updates_detected', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('survey_code')
    )
    op.create_index(op.f('ix_bls_survey_freshness_last_sentinel_check'), 'bls_survey_freshness', ['last_sentinel_check'], unique=False)
    op.create_index(op.f('ix_bls_survey_freshness_needs_full_update'), 'bls_survey_freshness', ['needs_full_update'], unique=False)
    op.create_table('bls_survey_sentinels',
    sa.Column('survey_code', sa.String(length=5), nullable=False),
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('sentinel_order', sa.Integer(), nullable=False),
    sa.Column('selection_reason', sa.String(length=50), nullable=True),
    sa.Column('last_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('last_year', sa.SmallInteger(), nullable=True),
    sa.Column('last_period', sa.String(length=5), nullable=True),
    sa.Column('last_footnotes', sa.String(length=500), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(), nullable=True),
    sa.Column('check_count', sa.Integer(), nullable=False),
    sa.Column('change_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('survey_code', 'series_id')
    )
    op.alter_column('bls_api_usage_log', 'execution_time',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_bls_api_usage_date'), table_name='bls_api_usage_log')
    op.create_index(op.f('ix_bls_api_usage_log_usage_date'), 'bls_api_usage_log', ['usage_date'], unique=False)
    op.alter_column('bls_series_update_status', 'is_current',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_bls_series_status_survey_current'), table_name='bls_series_update_status')
    op.create_index(op.f('ix_bls_series_update_status_is_current'), 'bls_series_update_status', ['is_current'], unique=False)
    op.create_index(op.f('ix_bls_series_update_status_survey_code'), 'bls_series_update_status', ['survey_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bls_series_update_status_survey_code'), table_name='bls_series_update_status')
    op.drop_index(op.f('ix_bls_series_update_status_is_current'), table_name='bls_series_update_status')
    op.create_index(op.f('ix_bls_series_status_survey_current'), 'bls_series_update_status', ['survey_code', 'is_current'], unique=False)
    op.alter_column('bls_series_update_status', 'is_current',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_bls_api_usage_log_usage_date'), table_name='bls_api_usage_log')
    op.create_index(op.f('ix_bls_api_usage_date'), 'bls_api_usage_log', ['usage_date'], unique=False)
    op.alter_column('bls_api_usage_log', 'execution_time',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_table('bls_survey_sentinels')
    op.drop_index(op.f('ix_bls_survey_freshness_needs_full_update'), table_name='bls_survey_freshness')
    op.drop_index(op.f('ix_bls_survey_freshness_last_sentinel_check'), table_name='bls_survey_freshness')
    op.drop_table('bls_survey_freshness')
    # ### end Alembic commands ###
