"""add_fixedassets_tables

Revision ID: 104fac9c69d9
Revises: 4f3eedfaa544
Create Date: 2025-12-02 13:30:18.855228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '104fac9c69d9'
down_revision: Union[str, Sequence[str], None] = '4f3eedfaa544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bea_fixedassets_tables',
    sa.Column('table_name', sa.String(length=20), nullable=False),
    sa.Column('table_description', sa.Text(), nullable=False),
    sa.Column('first_year', sa.SmallInteger(), nullable=True),
    sa.Column('last_year', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('table_name')
    )
    op.create_index('ix_bea_fixedassets_tables_active', 'bea_fixedassets_tables', ['is_active'], unique=False)
    op.create_table('bea_fixedassets_series',
    sa.Column('series_code', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=20), nullable=False),
    sa.Column('line_number', sa.SmallInteger(), nullable=False),
    sa.Column('line_description', sa.Text(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=True),
    sa.Column('cl_unit', sa.String(length=50), nullable=True),
    sa.Column('unit_mult', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_name'], ['bea_fixedassets_tables.table_name'], ),
    sa.PrimaryKeyConstraint('series_code')
    )
    op.create_index('ix_bea_fixedassets_series_active', 'bea_fixedassets_series', ['is_active'], unique=False)
    op.create_index('ix_bea_fixedassets_series_table_line', 'bea_fixedassets_series', ['table_name', 'line_number'], unique=False)
    op.create_index(op.f('ix_bea_fixedassets_series_table_name'), 'bea_fixedassets_series', ['table_name'], unique=False)
    op.create_table('bea_fixedassets_data',
    sa.Column('series_code', sa.String(length=50), nullable=False),
    sa.Column('time_period', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('note_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_code'], ['bea_fixedassets_series.series_code'], ),
    sa.PrimaryKeyConstraint('series_code', 'time_period')
    )
    op.create_index('ix_bea_fixedassets_data_period', 'bea_fixedassets_data', ['time_period'], unique=False)
    op.create_index('ix_bea_fixedassets_data_series', 'bea_fixedassets_data', ['series_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bea_fixedassets_data_series', table_name='bea_fixedassets_data')
    op.drop_index('ix_bea_fixedassets_data_period', table_name='bea_fixedassets_data')
    op.drop_table('bea_fixedassets_data')
    op.drop_index(op.f('ix_bea_fixedassets_series_table_name'), table_name='bea_fixedassets_series')
    op.drop_index('ix_bea_fixedassets_series_table_line', table_name='bea_fixedassets_series')
    op.drop_index('ix_bea_fixedassets_series_active', table_name='bea_fixedassets_series')
    op.drop_table('bea_fixedassets_series')
    op.drop_index('ix_bea_fixedassets_tables_active', table_name='bea_fixedassets_tables')
    op.drop_table('bea_fixedassets_tables')
    # ### end Alembic commands ###
