"""Add BLS CE (Current Employment Statistics) tables

Revision ID: 299241c31863
Revises: c2e4d0daa72b
Create Date: 2025-11-15 16:28:44.980372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299241c31863'
down_revision: Union[str, Sequence[str], None] = 'c2e4d0daa72b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_ce_data_types',
    sa.Column('data_type_code', sa.String(length=5), nullable=False),
    sa.Column('data_type_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('data_type_code')
    )
    op.create_table('bls_ce_industries',
    sa.Column('industry_code', sa.String(length=10), nullable=False),
    sa.Column('naics_code', sa.String(length=10), nullable=True),
    sa.Column('industry_name', sa.String(length=500), nullable=False),
    sa.Column('publishing_status', sa.String(length=1), nullable=True),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('industry_code')
    )
    op.create_index('ix_bls_ce_industries_level', 'bls_ce_industries', ['display_level'], unique=False)
    op.create_index('ix_bls_ce_industries_naics', 'bls_ce_industries', ['naics_code'], unique=False)
    op.create_table('bls_ce_supersectors',
    sa.Column('supersector_code', sa.String(length=5), nullable=False),
    sa.Column('supersector_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('supersector_code')
    )
    op.create_table('bls_ce_series',
    sa.Column('series_id', sa.String(length=20), nullable=False),
    sa.Column('supersector_code', sa.String(length=5), nullable=True),
    sa.Column('industry_code', sa.String(length=10), nullable=True),
    sa.Column('data_type_code', sa.String(length=5), nullable=True),
    sa.Column('seasonal_code', sa.String(length=1), nullable=True),
    sa.Column('series_title', sa.Text(), nullable=False),
    sa.Column('footnote_codes', sa.String(length=50), nullable=True),
    sa.Column('begin_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_period', sa.String(length=5), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_period', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_type_code'], ['bls_ce_data_types.data_type_code'], ),
    sa.ForeignKeyConstraint(['industry_code'], ['bls_ce_industries.industry_code'], ),
    sa.ForeignKeyConstraint(['supersector_code'], ['bls_ce_supersectors.supersector_code'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index('ix_bls_ce_series_active', 'bls_ce_series', ['is_active'], unique=False)
    op.create_index('ix_bls_ce_series_data_type', 'bls_ce_series', ['data_type_code'], unique=False)
    op.create_index('ix_bls_ce_series_industry', 'bls_ce_series', ['industry_code'], unique=False)
    op.create_index('ix_bls_ce_series_seasonal', 'bls_ce_series', ['seasonal_code'], unique=False)
    op.create_index('ix_bls_ce_series_supersector', 'bls_ce_series', ['supersector_code'], unique=False)
    op.create_table('bls_ce_data',
    sa.Column('series_id', sa.String(length=20), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=1), nullable=True),
    sa.Column('footnote_codes', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['bls_ce_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'year', 'period')
    )
    op.create_index('ix_bls_ce_data_series_year', 'bls_ce_data', ['series_id', 'year'], unique=False)
    op.create_index('ix_bls_ce_data_year_period', 'bls_ce_data', ['year', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bls_ce_data_year_period', table_name='bls_ce_data')
    op.drop_index('ix_bls_ce_data_series_year', table_name='bls_ce_data')
    op.drop_table('bls_ce_data')
    op.drop_index('ix_bls_ce_series_supersector', table_name='bls_ce_series')
    op.drop_index('ix_bls_ce_series_seasonal', table_name='bls_ce_series')
    op.drop_index('ix_bls_ce_series_industry', table_name='bls_ce_series')
    op.drop_index('ix_bls_ce_series_data_type', table_name='bls_ce_series')
    op.drop_index('ix_bls_ce_series_active', table_name='bls_ce_series')
    op.drop_table('bls_ce_series')
    op.drop_table('bls_ce_supersectors')
    op.drop_index('ix_bls_ce_industries_naics', table_name='bls_ce_industries')
    op.drop_index('ix_bls_ce_industries_level', table_name='bls_ce_industries')
    op.drop_table('bls_ce_industries')
    op.drop_table('bls_ce_data_types')
    # ### end Alembic commands ###
