"""add company profile bulk table

Revision ID: 29b60b2cb10f
Revises: 361c30c445b9
Create Date: 2025-11-14 00:06:45.109506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b60b2cb10f'
down_revision: Union[str, Sequence[str], None] = '361c30c445b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profile_bulk',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('beta', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('last_dividend', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('range', sa.String(length=50), nullable=True),
    sa.Column('change', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('change_percentage', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('average_volume', sa.BigInteger(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('cusip', sa.String(length=20), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('exchange_full_name', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ceo', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('full_time_employees', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('ipo_date', sa.String(length=20), nullable=True),
    sa.Column('default_image', sa.Boolean(), nullable=True),
    sa.Column('is_etf', sa.Boolean(), nullable=True),
    sa.Column('is_actively_trading', sa.Boolean(), nullable=True),
    sa.Column('is_adr', sa.Boolean(), nullable=True),
    sa.Column('is_fund', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_company_profile_bulk_symbol'), 'company_profile_bulk', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_profile_bulk_symbol'), table_name='company_profile_bulk')
    op.drop_table('company_profile_bulk')
    # ### end Alembic commands ###
