"""add price target summary bulk table

Revision ID: 361c30c445b9
Revises: c5a9d36f92cd
Create Date: 2025-11-13 23:42:59.894031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361c30c445b9'
down_revision: Union[str, Sequence[str], None] = 'c5a9d36f92cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_target_summary_bulk',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('last_month_count', sa.Integer(), nullable=True),
    sa.Column('last_month_avg_price_target', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('last_quarter_count', sa.Integer(), nullable=True),
    sa.Column('last_quarter_avg_price_target', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('last_year_count', sa.Integer(), nullable=True),
    sa.Column('last_year_avg_price_target', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('all_time_count', sa.Integer(), nullable=True),
    sa.Column('all_time_avg_price_target', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('publishers', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_price_target_summary_bulk_symbol'), 'price_target_summary_bulk', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_target_summary_bulk_symbol'), table_name='price_target_summary_bulk')
    op.drop_table('price_target_summary_bulk')
    # ### end Alembic commands ###
