"""add_nasdaq_screener_profiles_table

Revision ID: 394742ec64c0
Revises: a990dd38f509
Create Date: 2025-11-11 21:16:32.728133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '394742ec64c0'
down_revision: Union[str, Sequence[str], None] = 'a990dd38f509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nasdaq_screener_profiles',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('last_sale', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('net_change', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('percent_change', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('ipo_year', sa.Integer(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'snapshot_date')
    )
    op.create_index(op.f('ix_nasdaq_screener_profiles_sector'), 'nasdaq_screener_profiles', ['sector'], unique=False)
    op.create_index(op.f('ix_nasdaq_screener_profiles_symbol'), 'nasdaq_screener_profiles', ['symbol'], unique=False)
    op.create_index('ix_nasdaq_screener_sector', 'nasdaq_screener_profiles', ['sector'], unique=False)
    op.create_index('ix_nasdaq_screener_snapshot_date', 'nasdaq_screener_profiles', ['snapshot_date'], unique=False)
    op.create_index('ix_nasdaq_screener_symbol_date', 'nasdaq_screener_profiles', ['symbol', 'snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nasdaq_screener_symbol_date', table_name='nasdaq_screener_profiles')
    op.drop_index('ix_nasdaq_screener_snapshot_date', table_name='nasdaq_screener_profiles')
    op.drop_index('ix_nasdaq_screener_sector', table_name='nasdaq_screener_profiles')
    op.drop_index(op.f('ix_nasdaq_screener_profiles_symbol'), table_name='nasdaq_screener_profiles')
    op.drop_index(op.f('ix_nasdaq_screener_profiles_sector'), table_name='nasdaq_screener_profiles')
    op.drop_table('nasdaq_screener_profiles')
    # ### end Alembic commands ###
