"""Add BLS OE (Occupational Employment and Wage Statistics) tables

Revision ID: 444b0ef8d83c
Revises: 5875f0db9899
Create Date: 2025-11-16 01:48:31.772084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444b0ef8d83c'
down_revision: Union[str, Sequence[str], None] = '5875f0db9899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_oe_areas',
    sa.Column('area_code', sa.String(length=10), nullable=False),
    sa.Column('area_name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('area_code')
    )
    op.create_table('bls_oe_areatypes',
    sa.Column('areatype_code', sa.String(length=5), nullable=False),
    sa.Column('areatype_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('areatype_code')
    )
    op.create_table('bls_oe_datatypes',
    sa.Column('datatype_code', sa.String(length=5), nullable=False),
    sa.Column('datatype_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('datatype_code')
    )
    op.create_table('bls_oe_industries',
    sa.Column('industry_code', sa.String(length=10), nullable=False),
    sa.Column('industry_name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('industry_code')
    )
    op.create_table('bls_oe_occupations',
    sa.Column('occupation_code', sa.String(length=10), nullable=False),
    sa.Column('occupation_name', sa.String(length=500), nullable=False),
    sa.Column('occupation_description', sa.Text(), nullable=True),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('occupation_code')
    )
    op.create_table('bls_oe_sectors',
    sa.Column('sector_code', sa.String(length=10), nullable=False),
    sa.Column('sector_name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sector_code')
    )
    op.create_table('bls_oe_series',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('seasonal', sa.String(length=1), nullable=True),
    sa.Column('areatype_code', sa.String(length=5), nullable=True),
    sa.Column('industry_code', sa.String(length=10), nullable=True),
    sa.Column('occupation_code', sa.String(length=10), nullable=True),
    sa.Column('datatype_code', sa.String(length=5), nullable=True),
    sa.Column('state_code', sa.String(length=5), nullable=True),
    sa.Column('area_code', sa.String(length=10), nullable=True),
    sa.Column('sector_code', sa.String(length=10), nullable=True),
    sa.Column('series_title', sa.Text(), nullable=True),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('begin_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_period', sa.String(length=5), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_period', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_code'], ['bls_oe_areas.area_code'], ),
    sa.ForeignKeyConstraint(['areatype_code'], ['bls_oe_areatypes.areatype_code'], ),
    sa.ForeignKeyConstraint(['datatype_code'], ['bls_oe_datatypes.datatype_code'], ),
    sa.ForeignKeyConstraint(['industry_code'], ['bls_oe_industries.industry_code'], ),
    sa.ForeignKeyConstraint(['occupation_code'], ['bls_oe_occupations.occupation_code'], ),
    sa.ForeignKeyConstraint(['sector_code'], ['bls_oe_sectors.sector_code'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index('ix_bls_oe_series_active', 'bls_oe_series', ['is_active'], unique=False)
    op.create_index('ix_bls_oe_series_area', 'bls_oe_series', ['area_code'], unique=False)
    op.create_index('ix_bls_oe_series_datatype', 'bls_oe_series', ['datatype_code'], unique=False)
    op.create_index('ix_bls_oe_series_industry', 'bls_oe_series', ['industry_code'], unique=False)
    op.create_index('ix_bls_oe_series_occupation', 'bls_oe_series', ['occupation_code'], unique=False)
    op.create_table('bls_oe_data',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['bls_oe_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'year', 'period')
    )
    op.create_index('ix_bls_oe_data_series_year', 'bls_oe_data', ['series_id', 'year'], unique=False)
    op.create_index('ix_bls_oe_data_year_period', 'bls_oe_data', ['year', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bls_oe_data_year_period', table_name='bls_oe_data')
    op.drop_index('ix_bls_oe_data_series_year', table_name='bls_oe_data')
    op.drop_table('bls_oe_data')
    op.drop_index('ix_bls_oe_series_occupation', table_name='bls_oe_series')
    op.drop_index('ix_bls_oe_series_industry', table_name='bls_oe_series')
    op.drop_index('ix_bls_oe_series_datatype', table_name='bls_oe_series')
    op.drop_index('ix_bls_oe_series_area', table_name='bls_oe_series')
    op.drop_index('ix_bls_oe_series_active', table_name='bls_oe_series')
    op.drop_table('bls_oe_series')
    op.drop_table('bls_oe_sectors')
    op.drop_table('bls_oe_occupations')
    op.drop_table('bls_oe_industries')
    op.drop_table('bls_oe_datatypes')
    op.drop_table('bls_oe_areatypes')
    op.drop_table('bls_oe_areas')
    # ### end Alembic commands ###
