"""add GDPbyIndustry tables

Revision ID: 448b02687a4e
Revises: 946a41c247c0
Create Date: 2025-11-27 16:43:39.573308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448b02687a4e'
down_revision: Union[str, Sequence[str], None] = '946a41c247c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bea_gdpbyindustry_industries',
    sa.Column('industry_code', sa.String(length=20), nullable=False),
    sa.Column('industry_description', sa.Text(), nullable=False),
    sa.Column('parent_code', sa.String(length=20), nullable=True),
    sa.Column('industry_level', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('industry_code')
    )
    op.create_index('ix_bea_gdpbyindustry_industries_active', 'bea_gdpbyindustry_industries', ['is_active'], unique=False)
    op.create_index('ix_bea_gdpbyindustry_industries_parent', 'bea_gdpbyindustry_industries', ['parent_code'], unique=False)
    op.create_table('bea_gdpbyindustry_tables',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('table_description', sa.Text(), nullable=False),
    sa.Column('has_annual', sa.Boolean(), nullable=True),
    sa.Column('has_quarterly', sa.Boolean(), nullable=True),
    sa.Column('first_annual_year', sa.SmallInteger(), nullable=True),
    sa.Column('last_annual_year', sa.SmallInteger(), nullable=True),
    sa.Column('first_quarterly_year', sa.SmallInteger(), nullable=True),
    sa.Column('last_quarterly_year', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('table_id')
    )
    op.create_index('ix_bea_gdpbyindustry_tables_active', 'bea_gdpbyindustry_tables', ['is_active'], unique=False)
    op.create_table('bea_gdpbyindustry_data',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('industry_code', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=1), nullable=False),
    sa.Column('time_period', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('table_description', sa.Text(), nullable=True),
    sa.Column('industry_description', sa.Text(), nullable=True),
    sa.Column('cl_unit', sa.String(length=100), nullable=True),
    sa.Column('unit_mult', sa.SmallInteger(), nullable=True),
    sa.Column('note_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['industry_code'], ['bea_gdpbyindustry_industries.industry_code'], ),
    sa.ForeignKeyConstraint(['table_id'], ['bea_gdpbyindustry_tables.table_id'], ),
    sa.PrimaryKeyConstraint('table_id', 'industry_code', 'frequency', 'time_period')
    )
    op.create_index('ix_bea_gdpbyindustry_data_freq', 'bea_gdpbyindustry_data', ['frequency'], unique=False)
    op.create_index('ix_bea_gdpbyindustry_data_industry', 'bea_gdpbyindustry_data', ['industry_code'], unique=False)
    op.create_index('ix_bea_gdpbyindustry_data_period', 'bea_gdpbyindustry_data', ['time_period'], unique=False)
    op.create_index('ix_bea_gdpbyindustry_data_table', 'bea_gdpbyindustry_data', ['table_id'], unique=False)
    op.create_index('ix_bea_gdpbyindustry_data_table_industry', 'bea_gdpbyindustry_data', ['table_id', 'industry_code'], unique=False)
    op.create_index('ix_bea_gdpbyindustry_data_table_period', 'bea_gdpbyindustry_data', ['table_id', 'time_period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bea_gdpbyindustry_data_table_period', table_name='bea_gdpbyindustry_data')
    op.drop_index('ix_bea_gdpbyindustry_data_table_industry', table_name='bea_gdpbyindustry_data')
    op.drop_index('ix_bea_gdpbyindustry_data_table', table_name='bea_gdpbyindustry_data')
    op.drop_index('ix_bea_gdpbyindustry_data_period', table_name='bea_gdpbyindustry_data')
    op.drop_index('ix_bea_gdpbyindustry_data_industry', table_name='bea_gdpbyindustry_data')
    op.drop_index('ix_bea_gdpbyindustry_data_freq', table_name='bea_gdpbyindustry_data')
    op.drop_table('bea_gdpbyindustry_data')
    op.drop_index('ix_bea_gdpbyindustry_tables_active', table_name='bea_gdpbyindustry_tables')
    op.drop_table('bea_gdpbyindustry_tables')
    op.drop_index('ix_bea_gdpbyindustry_industries_parent', table_name='bea_gdpbyindustry_industries')
    op.drop_index('ix_bea_gdpbyindustry_industries_active', table_name='bea_gdpbyindustry_industries')
    op.drop_table('bea_gdpbyindustry_industries')
    # ### end Alembic commands ###
