"""Add BLS TU (American Time Use Survey) tables

Revision ID: 44c313f1d260
Revises: dbae27c5b3be
Create Date: 2025-11-16 08:50:17.265663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c313f1d260'
down_revision: Union[str, Sequence[str], None] = 'dbae27c5b3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_tu_actcodes',
    sa.Column('actcode_code', sa.String(length=10), nullable=False),
    sa.Column('actcode_text', sa.String(length=500), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('actcode_code')
    )
    op.create_table('bls_tu_ages',
    sa.Column('age_code', sa.String(length=10), nullable=False),
    sa.Column('age_text', sa.String(length=200), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('age_code')
    )
    op.create_table('bls_tu_education',
    sa.Column('educ_code', sa.String(length=5), nullable=False),
    sa.Column('educ_text', sa.String(length=300), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('educ_code')
    )
    op.create_table('bls_tu_labor_force_status',
    sa.Column('lfstat_code', sa.String(length=5), nullable=False),
    sa.Column('lfstat_text', sa.String(length=200), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('lfstat_code')
    )
    op.create_table('bls_tu_marital_status',
    sa.Column('maritlstat_code', sa.String(length=5), nullable=False),
    sa.Column('maritlstat_text', sa.String(length=300), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('maritlstat_code')
    )
    op.create_table('bls_tu_origin',
    sa.Column('orig_code', sa.String(length=5), nullable=False),
    sa.Column('orig_text', sa.String(length=200), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('orig_code')
    )
    op.create_table('bls_tu_races',
    sa.Column('race_code', sa.String(length=5), nullable=False),
    sa.Column('race_text', sa.String(length=200), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('race_code')
    )
    op.create_table('bls_tu_regions',
    sa.Column('region_code', sa.String(length=5), nullable=False),
    sa.Column('region_text', sa.String(length=200), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('region_code')
    )
    op.create_table('bls_tu_sex',
    sa.Column('sex_code', sa.String(length=5), nullable=False),
    sa.Column('sex_text', sa.String(length=100), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sex_code')
    )
    op.create_table('bls_tu_stattypes',
    sa.Column('stattype_code', sa.String(length=10), nullable=False),
    sa.Column('stattype_text', sa.String(length=500), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('stattype_code')
    )
    op.create_table('bls_tu_timeofday',
    sa.Column('timeday_code', sa.String(length=5), nullable=False),
    sa.Column('timeday_text', sa.String(length=200), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('timeday_code')
    )
    op.create_table('bls_tu_where',
    sa.Column('where_code', sa.String(length=5), nullable=False),
    sa.Column('where_text', sa.String(length=200), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('where_code')
    )
    op.create_table('bls_tu_who',
    sa.Column('who_code', sa.String(length=5), nullable=False),
    sa.Column('who_text', sa.String(length=200), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('who_code')
    )
    op.create_table('bls_tu_series',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('seasonal', sa.String(length=1), nullable=True),
    sa.Column('stattype_code', sa.String(length=10), nullable=True),
    sa.Column('datays_code', sa.String(length=5), nullable=True),
    sa.Column('sex_code', sa.String(length=5), nullable=True),
    sa.Column('region_code', sa.String(length=5), nullable=True),
    sa.Column('lfstat_code', sa.String(length=5), nullable=True),
    sa.Column('educ_code', sa.String(length=5), nullable=True),
    sa.Column('maritlstat_code', sa.String(length=5), nullable=True),
    sa.Column('age_code', sa.String(length=10), nullable=True),
    sa.Column('orig_code', sa.String(length=5), nullable=True),
    sa.Column('race_code', sa.String(length=5), nullable=True),
    sa.Column('mjcow_code', sa.String(length=5), nullable=True),
    sa.Column('nmet_code', sa.String(length=5), nullable=True),
    sa.Column('where_code', sa.String(length=5), nullable=True),
    sa.Column('sjmj_code', sa.String(length=5), nullable=True),
    sa.Column('timeday_code', sa.String(length=5), nullable=True),
    sa.Column('actcode_code', sa.String(length=10), nullable=True),
    sa.Column('industry_code', sa.String(length=10), nullable=True),
    sa.Column('occ_code', sa.String(length=10), nullable=True),
    sa.Column('prhhchild_code', sa.String(length=5), nullable=True),
    sa.Column('earn_code', sa.String(length=5), nullable=True),
    sa.Column('disability_code', sa.String(length=5), nullable=True),
    sa.Column('who_code', sa.String(length=5), nullable=True),
    sa.Column('hhnscc03_code', sa.String(length=5), nullable=True),
    sa.Column('schenr_code', sa.String(length=5), nullable=True),
    sa.Column('prownhhchild_code', sa.String(length=5), nullable=True),
    sa.Column('work_code', sa.String(length=5), nullable=True),
    sa.Column('elnum_code', sa.String(length=5), nullable=True),
    sa.Column('ecage_code', sa.String(length=10), nullable=True),
    sa.Column('elfreq_code', sa.String(length=5), nullable=True),
    sa.Column('eldur_code', sa.String(length=5), nullable=True),
    sa.Column('elwho_code', sa.String(length=5), nullable=True),
    sa.Column('ecytd_code', sa.String(length=5), nullable=True),
    sa.Column('elder_code', sa.String(length=5), nullable=True),
    sa.Column('lfstatw_code', sa.String(length=5), nullable=True),
    sa.Column('pertype_code', sa.String(length=5), nullable=True),
    sa.Column('series_title', sa.Text(), nullable=True),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('begin_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_period', sa.String(length=5), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_period', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actcode_code'], ['bls_tu_actcodes.actcode_code'], ),
    sa.ForeignKeyConstraint(['age_code'], ['bls_tu_ages.age_code'], ),
    sa.ForeignKeyConstraint(['educ_code'], ['bls_tu_education.educ_code'], ),
    sa.ForeignKeyConstraint(['lfstat_code'], ['bls_tu_labor_force_status.lfstat_code'], ),
    sa.ForeignKeyConstraint(['maritlstat_code'], ['bls_tu_marital_status.maritlstat_code'], ),
    sa.ForeignKeyConstraint(['orig_code'], ['bls_tu_origin.orig_code'], ),
    sa.ForeignKeyConstraint(['race_code'], ['bls_tu_races.race_code'], ),
    sa.ForeignKeyConstraint(['region_code'], ['bls_tu_regions.region_code'], ),
    sa.ForeignKeyConstraint(['sex_code'], ['bls_tu_sex.sex_code'], ),
    sa.ForeignKeyConstraint(['stattype_code'], ['bls_tu_stattypes.stattype_code'], ),
    sa.ForeignKeyConstraint(['timeday_code'], ['bls_tu_timeofday.timeday_code'], ),
    sa.ForeignKeyConstraint(['where_code'], ['bls_tu_where.where_code'], ),
    sa.ForeignKeyConstraint(['who_code'], ['bls_tu_who.who_code'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index('ix_bls_tu_series_actcode', 'bls_tu_series', ['actcode_code'], unique=False)
    op.create_index('ix_bls_tu_series_active', 'bls_tu_series', ['is_active'], unique=False)
    op.create_index('ix_bls_tu_series_age', 'bls_tu_series', ['age_code'], unique=False)
    op.create_index('ix_bls_tu_series_sex', 'bls_tu_series', ['sex_code'], unique=False)
    op.create_index('ix_bls_tu_series_stattype', 'bls_tu_series', ['stattype_code'], unique=False)
    op.create_table('bls_tu_aspect',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('aspect_type', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=3), nullable=True),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['bls_tu_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'year', 'period', 'aspect_type')
    )
    op.create_index('ix_bls_tu_aspect_series_year', 'bls_tu_aspect', ['series_id', 'year'], unique=False)
    op.create_index('ix_bls_tu_aspect_year_period', 'bls_tu_aspect', ['year', 'period'], unique=False)
    op.create_table('bls_tu_data',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=3), nullable=True),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['bls_tu_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'year', 'period')
    )
    op.create_index('ix_bls_tu_data_series_year', 'bls_tu_data', ['series_id', 'year'], unique=False)
    op.create_index('ix_bls_tu_data_year_period', 'bls_tu_data', ['year', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bls_tu_data_year_period', table_name='bls_tu_data')
    op.drop_index('ix_bls_tu_data_series_year', table_name='bls_tu_data')
    op.drop_table('bls_tu_data')
    op.drop_index('ix_bls_tu_aspect_year_period', table_name='bls_tu_aspect')
    op.drop_index('ix_bls_tu_aspect_series_year', table_name='bls_tu_aspect')
    op.drop_table('bls_tu_aspect')
    op.drop_index('ix_bls_tu_series_stattype', table_name='bls_tu_series')
    op.drop_index('ix_bls_tu_series_sex', table_name='bls_tu_series')
    op.drop_index('ix_bls_tu_series_age', table_name='bls_tu_series')
    op.drop_index('ix_bls_tu_series_active', table_name='bls_tu_series')
    op.drop_index('ix_bls_tu_series_actcode', table_name='bls_tu_series')
    op.drop_table('bls_tu_series')
    op.drop_table('bls_tu_who')
    op.drop_table('bls_tu_where')
    op.drop_table('bls_tu_timeofday')
    op.drop_table('bls_tu_stattypes')
    op.drop_table('bls_tu_sex')
    op.drop_table('bls_tu_regions')
    op.drop_table('bls_tu_races')
    op.drop_table('bls_tu_origin')
    op.drop_table('bls_tu_marital_status')
    op.drop_table('bls_tu_labor_force_status')
    op.drop_table('bls_tu_education')
    op.drop_table('bls_tu_ages')
    op.drop_table('bls_tu_actcodes')
    # ### end Alembic commands ###
