"""Add BLS WP (Producer Price Index - Commodities) tables

Revision ID: 45ee62d5af26
Revises: e56e8f904096
Create Date: 2025-11-15 18:52:56.752659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ee62d5af26'
down_revision: Union[str, Sequence[str], None] = 'e56e8f904096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_wp_groups',
    sa.Column('group_code', sa.String(length=10), nullable=False),
    sa.Column('group_name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('group_code')
    )
    op.create_table('bls_wp_items',
    sa.Column('group_code', sa.String(length=10), nullable=False),
    sa.Column('item_code', sa.String(length=20), nullable=False),
    sa.Column('item_name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_code'], ['bls_wp_groups.group_code'], ),
    sa.PrimaryKeyConstraint('group_code', 'item_code')
    )
    op.create_table('bls_wp_series',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('group_code', sa.String(length=10), nullable=True),
    sa.Column('item_code', sa.String(length=20), nullable=True),
    sa.Column('seasonal_code', sa.String(length=1), nullable=True),
    sa.Column('base_date', sa.String(length=10), nullable=True),
    sa.Column('series_title', sa.Text(), nullable=False),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('begin_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_period', sa.String(length=5), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_period', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_code'], ['bls_wp_groups.group_code'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index('ix_bls_wp_series_active', 'bls_wp_series', ['is_active'], unique=False)
    op.create_index('ix_bls_wp_series_group', 'bls_wp_series', ['group_code'], unique=False)
    op.create_index('ix_bls_wp_series_seasonal', 'bls_wp_series', ['seasonal_code'], unique=False)
    op.create_table('bls_wp_data',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=3), nullable=True),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['bls_wp_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'year', 'period')
    )
    op.create_index('ix_bls_wp_data_series_year', 'bls_wp_data', ['series_id', 'year'], unique=False)
    op.create_index('ix_bls_wp_data_year_period', 'bls_wp_data', ['year', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bls_wp_data_year_period', table_name='bls_wp_data')
    op.drop_index('ix_bls_wp_data_series_year', table_name='bls_wp_data')
    op.drop_table('bls_wp_data')
    op.drop_index('ix_bls_wp_series_seasonal', table_name='bls_wp_series')
    op.drop_index('ix_bls_wp_series_group', table_name='bls_wp_series')
    op.drop_index('ix_bls_wp_series_active', table_name='bls_wp_series')
    op.drop_table('bls_wp_series')
    op.drop_table('bls_wp_items')
    op.drop_table('bls_wp_groups')
    # ### end Alembic commands ###
