"""Add BLS AP tables

Revision ID: 4770a74e36cc
Revises: 29b60b2cb10f
Create Date: 2025-11-15 12:05:25.627937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4770a74e36cc'
down_revision: Union[str, Sequence[str], None] = '29b60b2cb10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_ap_items',
    sa.Column('item_code', sa.String(length=10), nullable=False),
    sa.Column('item_name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('item_code')
    )
    op.create_table('bls_areas',
    sa.Column('area_code', sa.String(length=10), nullable=False),
    sa.Column('area_name', sa.String(length=255), nullable=False),
    sa.Column('area_type', sa.String(length=50), nullable=True),
    sa.Column('parent_area_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('area_code')
    )
    op.create_index('ix_bls_areas_type', 'bls_areas', ['area_type'], unique=False)
    op.create_table('bls_periods',
    sa.Column('period_code', sa.String(length=5), nullable=False),
    sa.Column('period_abbr', sa.String(length=10), nullable=True),
    sa.Column('period_name', sa.String(length=50), nullable=True),
    sa.Column('period_type', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('period_code')
    )
    op.create_table('bls_surveys',
    sa.Column('survey_code', sa.String(length=10), nullable=False),
    sa.Column('survey_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('has_seasonal_adjustment', sa.Boolean(), nullable=True),
    sa.Column('has_annual_averages', sa.Boolean(), nullable=True),
    sa.Column('has_calculations', sa.Boolean(), nullable=True),
    sa.Column('doc_url', sa.String(length=500), nullable=True),
    sa.Column('series_id_format_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('survey_code')
    )
    op.create_table('bls_ap_series',
    sa.Column('series_id', sa.String(length=20), nullable=False),
    sa.Column('seasonal_code', sa.String(length=1), nullable=True),
    sa.Column('area_code', sa.String(length=10), nullable=True),
    sa.Column('item_code', sa.String(length=10), nullable=True),
    sa.Column('series_title', sa.Text(), nullable=False),
    sa.Column('begin_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_period', sa.String(length=5), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_period', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_code'], ['bls_areas.area_code'], ),
    sa.ForeignKeyConstraint(['item_code'], ['bls_ap_items.item_code'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index('ix_bls_ap_series_active', 'bls_ap_series', ['is_active'], unique=False)
    op.create_index('ix_bls_ap_series_area', 'bls_ap_series', ['area_code'], unique=False)
    op.create_index('ix_bls_ap_series_item', 'bls_ap_series', ['item_code'], unique=False)
    op.create_table('bls_ap_data',
    sa.Column('series_id', sa.String(length=20), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('footnote_codes', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['bls_ap_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'year', 'period')
    )
    op.create_index('ix_bls_ap_data_series_year', 'bls_ap_data', ['series_id', 'year'], unique=False)
    op.create_index('ix_bls_ap_data_year_period', 'bls_ap_data', ['year', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bls_ap_data_year_period', table_name='bls_ap_data')
    op.drop_index('ix_bls_ap_data_series_year', table_name='bls_ap_data')
    op.drop_table('bls_ap_data')
    op.drop_index('ix_bls_ap_series_item', table_name='bls_ap_series')
    op.drop_index('ix_bls_ap_series_area', table_name='bls_ap_series')
    op.drop_index('ix_bls_ap_series_active', table_name='bls_ap_series')
    op.drop_table('bls_ap_series')
    op.drop_table('bls_surveys')
    op.drop_table('bls_periods')
    op.drop_index('ix_bls_areas_type', table_name='bls_areas')
    op.drop_table('bls_areas')
    op.drop_table('bls_ap_items')
    # ### end Alembic commands ###
