"""replace_prices_daily_with_adjusted_prices

Revision ID: 4a29b6231995
Revises: a49c4f25c8d7
Create Date: 2025-11-09 15:07:20.279682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a29b6231995'
down_revision: Union[str, Sequence[str], None] = 'a49c4f25c8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices_daily', sa.Column('adj_open', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('prices_daily', sa.Column('adj_high', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('prices_daily', sa.Column('adj_low', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('prices_daily', sa.Column('adj_close', sa.Numeric(precision=20, scale=4), nullable=True))
    op.drop_column('prices_daily', 'vwap')
    op.drop_column('prices_daily', 'high')
    op.drop_column('prices_daily', 'change_percent')
    op.drop_column('prices_daily', 'change')
    op.drop_column('prices_daily', 'close')
    op.drop_column('prices_daily', 'open')
    op.drop_column('prices_daily', 'low')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices_daily', sa.Column('low', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
    op.add_column('prices_daily', sa.Column('open', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
    op.add_column('prices_daily', sa.Column('close', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
    op.add_column('prices_daily', sa.Column('change', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
    op.add_column('prices_daily', sa.Column('change_percent', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=True))
    op.add_column('prices_daily', sa.Column('high', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
    op.add_column('prices_daily', sa.Column('vwap', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
    op.drop_column('prices_daily', 'adj_close')
    op.drop_column('prices_daily', 'adj_low')
    op.drop_column('prices_daily', 'adj_high')
    op.drop_column('prices_daily', 'adj_open')
    # ### end Alembic commands ###
