"""increase_collection_runs_frequency_size

Revision ID: 4f3eedfaa544
Revises: 5e6889152bca
Create Date: 2025-12-01 09:34:18.539923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f3eedfaa544'
down_revision: Union[str, Sequence[str], None] = '5e6889152bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bea_collection_runs', 'frequency',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bea_collection_runs', 'frequency',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
    # ### end Alembic commands ###
