"""fix key metrics ttm bulk field types - drop and recreate

Revision ID: 548089846f02
Revises: 6eab4c30b690
Create Date: 2025-11-13 23:23:06.180641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548089846f02'
down_revision: Union[str, Sequence[str], None] = '6eab4c30b690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('key_metrics_ttm_bulk', 'ev_to_sales_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'ev_to_operating_cash_flow_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'ev_to_free_cash_flow_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'ev_to_ebitda_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'net_debt_to_ebitda_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'current_ratio_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'income_quality_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'graham_number_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'graham_net_net_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'tax_burden_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'interest_burden_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'return_on_assets_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'operating_return_on_assets_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'return_on_tangible_assets_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'return_on_equity_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'return_on_invested_capital_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'return_on_capital_employed_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'earnings_yield_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'free_cash_flow_yield_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'capex_to_operating_cash_flow_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'capex_to_depreciation_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'capex_to_revenue_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'sales_general_and_administrative_to_revenue_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'research_and_developement_to_revenue_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'stock_based_compensation_to_revenue_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'intangibles_to_total_assets_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'days_of_sales_outstanding_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'days_of_payables_outstanding_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'days_of_inventory_outstanding_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'operating_cycle_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'cash_conversion_cycle_ttm',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('key_metrics_ttm_bulk', 'cash_conversion_cycle_ttm',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'operating_cycle_ttm',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'days_of_inventory_outstanding_ttm',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'days_of_payables_outstanding_ttm',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'days_of_sales_outstanding_ttm',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'intangibles_to_total_assets_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'stock_based_compensation_to_revenue_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'research_and_developement_to_revenue_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'sales_general_and_administrative_to_revenue_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'capex_to_revenue_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'capex_to_depreciation_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'capex_to_operating_cash_flow_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'free_cash_flow_yield_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'earnings_yield_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'return_on_capital_employed_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'return_on_invested_capital_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'return_on_equity_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'return_on_tangible_assets_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'operating_return_on_assets_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'return_on_assets_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'interest_burden_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'tax_burden_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'graham_net_net_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'graham_number_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'income_quality_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'current_ratio_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'net_debt_to_ebitda_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'ev_to_ebitda_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'ev_to_free_cash_flow_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'ev_to_operating_cash_flow_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('key_metrics_ttm_bulk', 'ev_to_sales_ttm',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=True)
    # ### end Alembic commands ###
