"""Add BLS EC (Employment Cost Index) tables

Revision ID: 5875f0db9899
Revises: efeaf077ec52
Create Date: 2025-11-16 01:18:42.449620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5875f0db9899'
down_revision: Union[str, Sequence[str], None] = 'efeaf077ec52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_ec_compensations',
    sa.Column('comp_code', sa.String(length=5), nullable=False),
    sa.Column('comp_text', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('comp_code')
    )
    op.create_table('bls_ec_groups',
    sa.Column('group_code', sa.String(length=10), nullable=False),
    sa.Column('group_name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('group_code')
    )
    op.create_table('bls_ec_ownerships',
    sa.Column('ownership_code', sa.String(length=5), nullable=False),
    sa.Column('ownership_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ownership_code')
    )
    op.create_table('bls_ec_periodicities',
    sa.Column('periodicity_code', sa.String(length=5), nullable=False),
    sa.Column('periodicity_text', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('periodicity_code')
    )
    op.create_table('bls_ec_series',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('comp_code', sa.String(length=5), nullable=True),
    sa.Column('group_code', sa.String(length=10), nullable=True),
    sa.Column('ownership_code', sa.String(length=5), nullable=True),
    sa.Column('periodicity_code', sa.String(length=5), nullable=True),
    sa.Column('seasonal', sa.String(length=1), nullable=True),
    sa.Column('begin_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_period', sa.String(length=5), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_period', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comp_code'], ['bls_ec_compensations.comp_code'], ),
    sa.ForeignKeyConstraint(['group_code'], ['bls_ec_groups.group_code'], ),
    sa.ForeignKeyConstraint(['ownership_code'], ['bls_ec_ownerships.ownership_code'], ),
    sa.ForeignKeyConstraint(['periodicity_code'], ['bls_ec_periodicities.periodicity_code'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index('ix_bls_ec_series_active', 'bls_ec_series', ['is_active'], unique=False)
    op.create_index('ix_bls_ec_series_comp', 'bls_ec_series', ['comp_code'], unique=False)
    op.create_index('ix_bls_ec_series_group', 'bls_ec_series', ['group_code'], unique=False)
    op.create_index('ix_bls_ec_series_ownership', 'bls_ec_series', ['ownership_code'], unique=False)
    op.create_index('ix_bls_ec_series_seasonal', 'bls_ec_series', ['seasonal'], unique=False)
    op.create_table('bls_ec_data',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=3), nullable=True),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['bls_ec_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'year', 'period')
    )
    op.create_index('ix_bls_ec_data_series_year', 'bls_ec_data', ['series_id', 'year'], unique=False)
    op.create_index('ix_bls_ec_data_year_period', 'bls_ec_data', ['year', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bls_ec_data_year_period', table_name='bls_ec_data')
    op.drop_index('ix_bls_ec_data_series_year', table_name='bls_ec_data')
    op.drop_table('bls_ec_data')
    op.drop_index('ix_bls_ec_series_seasonal', table_name='bls_ec_series')
    op.drop_index('ix_bls_ec_series_ownership', table_name='bls_ec_series')
    op.drop_index('ix_bls_ec_series_group', table_name='bls_ec_series')
    op.drop_index('ix_bls_ec_series_comp', table_name='bls_ec_series')
    op.drop_index('ix_bls_ec_series_active', table_name='bls_ec_series')
    op.drop_table('bls_ec_series')
    op.drop_table('bls_ec_periodicities')
    op.drop_table('bls_ec_ownerships')
    op.drop_table('bls_ec_groups')
    op.drop_table('bls_ec_compensations')
    # ### end Alembic commands ###
