"""Add prices_daily_bulk table

Revision ID: 5a60fd1812da
Revises: 8e943526d658
Create Date: 2025-11-05 19:40:31.332203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a60fd1812da'
down_revision: Union[str, Sequence[str], None] = '8e943526d658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices_daily_bulk',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_index('ix_prices_daily_bulk_date', 'prices_daily_bulk', ['date'], unique=False)
    op.create_index('ix_prices_daily_bulk_symbol', 'prices_daily_bulk', ['symbol'], unique=False)
    op.create_index('ix_prices_daily_bulk_symbol_date', 'prices_daily_bulk', ['symbol', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_daily_bulk_symbol_date', table_name='prices_daily_bulk')
    op.drop_index('ix_prices_daily_bulk_symbol', table_name='prices_daily_bulk')
    op.drop_index('ix_prices_daily_bulk_date', table_name='prices_daily_bulk')
    op.drop_table('prices_daily_bulk')
    # ### end Alembic commands ###
