"""add_economic_calendar_table

Revision ID: 61bf6a771bfa
Revises: c7f20147e5e3
Create Date: 2025-11-06 20:42:20.371196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bf6a771bfa'
down_revision: Union[str, Sequence[str], None] = 'c7f20147e5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_calendar',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('event', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('previous', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('estimate', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('actual', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('change', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('change_percentage', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('impact', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'country', 'event')
    )
    op.create_index('ix_economic_calendar_country', 'economic_calendar', ['country'], unique=False)
    op.create_index('ix_economic_calendar_date', 'economic_calendar', ['date'], unique=False)
    op.create_index('ix_economic_calendar_impact', 'economic_calendar', ['impact'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_economic_calendar_impact', table_name='economic_calendar')
    op.drop_index('ix_economic_calendar_date', table_name='economic_calendar')
    op.drop_index('ix_economic_calendar_country', table_name='economic_calendar')
    op.drop_table('economic_calendar')
    # ### end Alembic commands ###
