"""initial schema

Revision ID: 63ccfe5a2ad8
Revises: 
Create Date: 2025-11-02 23:20:45.329379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ccfe5a2ad8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('beta', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('last_dividend', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('range', sa.String(length=50), nullable=True),
    sa.Column('change', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('change_percentage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('average_volume', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('cusip', sa.String(length=20), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('exchange_full_name', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ceo', sa.String(length=100), nullable=True),
    sa.Column('full_time_employees', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('ipo_date', sa.Date(), nullable=True),
    sa.Column('default_image', sa.Boolean(), nullable=True),
    sa.Column('is_etf', sa.Boolean(), nullable=True),
    sa.Column('is_actively_trading', sa.Boolean(), nullable=True),
    sa.Column('is_adr', sa.Boolean(), nullable=True),
    sa.Column('is_fund', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_sector'), 'companies', ['sector'], unique=False)
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=True)
    op.create_table('data_collection_log',
    sa.Column('run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('companies_requested', sa.Integer(), nullable=True),
    sa.Column('companies_processed', sa.Integer(), nullable=True),
    sa.Column('companies_failed', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('ix_collection_log_job_start', 'data_collection_log', ['job_name', 'start_time'], unique=False)
    op.create_index('ix_collection_log_status', 'data_collection_log', ['status'], unique=False)
    op.create_index(op.f('ix_data_collection_log_job_name'), 'data_collection_log', ['job_name'], unique=False)
    op.create_table('economic_indicators',
    sa.Column('indicator_name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('series_id', sa.String(length=50), nullable=True),
    sa.Column('units', sa.String(length=100), nullable=True),
    sa.Column('seasonal_adjustment', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('indicator_name', 'date')
    )
    op.create_index('ix_economic_indicators_date', 'economic_indicators', ['date'], unique=False)
    op.create_index('ix_economic_indicators_name_date', 'economic_indicators', ['indicator_name', 'date'], unique=False)
    op.create_table('table_update_tracking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('last_update_timestamp', sa.DateTime(), nullable=False),
    sa.Column('last_api_date', sa.Date(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('next_update_due', sa.DateTime(), nullable=True),
    sa.Column('update_frequency', sa.String(length=20), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_errors', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name', 'symbol', name='uq_table_symbol')
    )
    op.create_index(op.f('ix_table_update_tracking_symbol'), 'table_update_tracking', ['symbol'], unique=False)
    op.create_index(op.f('ix_table_update_tracking_table_name'), 'table_update_tracking', ['table_name'], unique=False)
    op.create_index('ix_update_tracking_next_due', 'table_update_tracking', ['next_update_due'], unique=False)
    op.create_index('ix_update_tracking_table_symbol', 'table_update_tracking', ['table_name', 'symbol'], unique=False)
    op.create_table('analyst_estimates',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('revenue_low', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('revenue_high', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('revenue_avg', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('num_analysts_revenue', sa.Integer(), nullable=True),
    sa.Column('net_income_low', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_income_high', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_income_avg', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebit_low', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebit_high', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebit_avg', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebitda_low', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebitda_high', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebitda_avg', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('eps_avg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_high', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_low', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('num_analysts_eps', sa.Integer(), nullable=True),
    sa.Column('sga_expense_low', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('sga_expense_high', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('sga_expense_avg', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_index('ix_analyst_estimates_symbol_date', 'analyst_estimates', ['date'], unique=False)
    op.create_table('balance_sheets',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('reported_currency', sa.String(length=10), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('filling_date', sa.Date(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('accepted_date', sa.DateTime(), nullable=True),
    sa.Column('calendar_year', sa.String(length=10), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('cash_and_cash_equivalents', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('short_term_investments', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cash_and_short_term_investments', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_receivables', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('accounts_receivables', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_receivables', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('inventory', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('prepaids', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_current_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_current_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('property_plant_equipment_net', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('goodwill', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('intangible_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('goodwill_and_intangible_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('long_term_investments', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('tax_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_non_current_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_non_current_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_payables', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('account_payables', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_payables', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('accrued_expenses', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('short_term_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('capital_lease_obligations_current', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('capital_lease_obligations_non_current', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('tax_payables', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('deferred_revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_current_liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_current_liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('long_term_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('deferred_revenue_non_current', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('deferred_tax_liabilities_non_current', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_non_current_liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_non_current_liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('capital_lease_obligations', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('treasury_stock', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('preferred_stock', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('common_stock', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('retained_earnings', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('additional_paid_in_capital', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('accumulated_other_comprehensive_income_loss', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_total_stockholders_equity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_stockholders_equity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('minority_interest', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_liabilities_and_total_equity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_investments', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date', 'period')
    )
    op.create_index('ix_balance_sheets_fiscal_year', 'balance_sheets', ['fiscal_year'], unique=False)
    op.create_index('ix_balance_sheets_symbol_date', 'balance_sheets', ['symbol', 'date'], unique=False)
    op.create_table('cash_flows',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('reported_currency', sa.String(length=10), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('accepted_date', sa.DateTime(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('depreciation_and_amortization', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('deferred_income_tax', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('stock_based_compensation', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('change_in_working_capital', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('accounts_receivables', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('inventory', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('accounts_payables', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_working_capital', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_non_cash_items', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_cash_provided_by_operating_activities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('investments_in_property_plant_and_equipment', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('acquisitions_net', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('purchases_of_investments', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('sales_maturities_of_investments', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_investing_activities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_cash_provided_by_investing_activities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_debt_issuance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('long_term_net_debt_issuance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('short_term_net_debt_issuance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_stock_issuance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_common_stock_issuance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('common_stock_issuance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('common_stock_repurchased', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_preferred_stock_issuance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_dividends_paid', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('common_dividends_paid', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('preferred_dividends_paid', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_financing_activities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_cash_provided_by_financing_activities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('effect_of_forex_changes_on_cash', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_change_in_cash', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cash_at_end_of_period', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cash_at_beginning_of_period', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('capital_expenditure', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('income_taxes_paid', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('interest_paid', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date', 'period')
    )
    op.create_index('ix_cash_flows_fiscal_year', 'cash_flows', ['fiscal_year'], unique=False)
    op.create_index('ix_cash_flows_symbol_date', 'cash_flows', ['symbol', 'date'], unique=False)
    op.create_table('employee_history',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('period_of_report', sa.Date(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('acceptance_time', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('form_type', sa.String(length=20), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'period_of_report')
    )
    op.create_index('ix_employee_history_symbol_period', 'employee_history', ['symbol', 'period_of_report'], unique=False)
    op.create_table('enterprise_values',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stock_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('number_of_shares', sa.BigInteger(), nullable=True),
    sa.Column('market_capitalization', sa.BigInteger(), nullable=True),
    sa.Column('minus_cash_and_cash_equivalents', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('add_total_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('enterprise_value', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_index('ix_enterprise_values_symbol_date', 'enterprise_values', ['symbol', 'date'], unique=False)
    op.create_table('financial_ratios',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('reported_currency', sa.String(length=10), nullable=True),
    sa.Column('gross_profit_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('ebit_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('ebitda_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('operating_profit_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('pretax_profit_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('continuous_operations_profit_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('net_profit_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('bottom_line_profit_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('receivables_turnover', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('payables_turnover', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('inventory_turnover', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fixed_asset_turnover', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('asset_turnover', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('quick_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('solvency_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cash_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('price_to_earnings_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('price_to_earnings_growth_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('forward_price_to_earnings_growth_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('price_to_book_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('price_to_sales_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('price_to_free_cash_flow_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('price_to_operating_cash_flow_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('debt_to_assets_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('debt_to_equity_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('debt_to_capital_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('long_term_debt_to_capital_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('financial_leverage_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('working_capital_turnover_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('operating_cash_flow_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('operating_cash_flow_sales_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('free_cash_flow_operating_cash_flow_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('debt_service_coverage_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('interest_coverage_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('short_term_operating_cash_flow_coverage_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('operating_cash_flow_coverage_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('capital_expenditure_coverage_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('dividend_paid_and_capex_coverage_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('dividend_payout_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('dividend_yield_percentage', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('revenue_per_share', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('net_income_per_share', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('dividend_per_share', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('interest_debt_per_share', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('cash_per_share', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('book_value_per_share', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('tangible_book_value_per_share', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('shareholders_equity_per_share', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('operating_cash_flow_per_share', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('capex_per_share', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('free_cash_flow_per_share', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('net_income_per_ebt', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('ebt_per_ebit', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('price_to_fair_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('debt_to_market_cap', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('effective_tax_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('enterprise_value_multiple', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date', 'period')
    )
    op.create_index('ix_financial_ratios_fiscal_year', 'financial_ratios', ['fiscal_year'], unique=False)
    op.create_index('ix_financial_ratios_symbol_date', 'financial_ratios', ['symbol', 'date'], unique=False)
    op.create_table('income_statements',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('reported_currency', sa.String(length=10), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('filling_date', sa.Date(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('accepted_date', sa.DateTime(), nullable=True),
    sa.Column('calendar_year', sa.String(length=10), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cost_of_revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('gross_profit_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('research_and_development_expenses', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('general_and_administrative_expenses', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('selling_and_marketing_expenses', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('selling_general_and_administrative_expenses', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_expenses', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_expenses', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cost_and_expenses', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('interest_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('interest_expense', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_interest_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('depreciation_and_amortization', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebitda_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('ebit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('non_operating_income_excluding_interest', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_income_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('total_other_income_expenses_net', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('income_before_tax', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('income_before_tax_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('income_tax_expense', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_income_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('net_income_from_continuing_operations', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_income_from_discontinued_operations', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_adjustments_to_net_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_income_deductions', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('bottom_line_net_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('eps', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('eps_diluted', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('weighted_average_shs_out', sa.BigInteger(), nullable=True),
    sa.Column('weighted_average_shs_out_dil', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date', 'period')
    )
    op.create_index('ix_income_statements_fiscal_year', 'income_statements', ['fiscal_year'], unique=False)
    op.create_index('ix_income_statements_symbol_date', 'income_statements', ['symbol', 'date'], unique=False)
    op.create_table('insider_statistics',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('acquired_transactions', sa.Integer(), nullable=True),
    sa.Column('disposed_transactions', sa.Integer(), nullable=True),
    sa.Column('acquired_disposed_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('total_acquired', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_disposed', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_sales', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_purchases', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('average_acquired', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('average_disposed', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'year', 'quarter')
    )
    op.create_index(op.f('ix_insider_statistics_cik'), 'insider_statistics', ['cik'], unique=False)
    op.create_index('ix_insider_statistics_symbol_year_quarter', 'insider_statistics', ['year', 'quarter'], unique=False)
    op.create_table('insider_trading',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('reporting_cik', sa.String(length=20), nullable=True),
    sa.Column('company_cik', sa.String(length=20), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('securities_owned', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('reporting_name', sa.String(length=200), nullable=True),
    sa.Column('type_of_owner', sa.String(length=100), nullable=True),
    sa.Column('acquisition_or_disposition', sa.String(length=1), nullable=True),
    sa.Column('direct_or_indirect', sa.String(length=1), nullable=True),
    sa.Column('form_type', sa.String(length=20), nullable=True),
    sa.Column('securities_transacted', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('security_name', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insider_trading_filing_date'), 'insider_trading', ['filing_date'], unique=False)
    op.create_index(op.f('ix_insider_trading_symbol'), 'insider_trading', ['symbol'], unique=False)
    op.create_index('ix_insider_trading_symbol_filing_date', 'insider_trading', ['symbol', 'filing_date'], unique=False)
    op.create_index('ix_insider_trading_symbol_transaction_date', 'insider_trading', ['symbol', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_insider_trading_transaction_date'), 'insider_trading', ['transaction_date'], unique=False)
    op.create_table('institutional_ownership',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('investors_holding', sa.Integer(), nullable=True),
    sa.Column('last_investors_holding', sa.Integer(), nullable=True),
    sa.Column('investors_holding_change', sa.Integer(), nullable=True),
    sa.Column('number_of_13_fshares', sa.BigInteger(), nullable=True),
    sa.Column('last_number_of_13_fshares', sa.BigInteger(), nullable=True),
    sa.Column('number_of_13_fshares_change', sa.BigInteger(), nullable=True),
    sa.Column('total_invested', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('last_total_invested', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_invested_change', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ownership_percent', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('last_ownership_percent', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('ownership_percent_change', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('new_positions', sa.Integer(), nullable=True),
    sa.Column('last_new_positions', sa.Integer(), nullable=True),
    sa.Column('new_positions_change', sa.Integer(), nullable=True),
    sa.Column('increased_positions', sa.Integer(), nullable=True),
    sa.Column('last_increased_positions', sa.Integer(), nullable=True),
    sa.Column('increased_positions_change', sa.Integer(), nullable=True),
    sa.Column('closed_positions', sa.Integer(), nullable=True),
    sa.Column('last_closed_positions', sa.Integer(), nullable=True),
    sa.Column('closed_positions_change', sa.Integer(), nullable=True),
    sa.Column('reduced_positions', sa.Integer(), nullable=True),
    sa.Column('last_reduced_positions', sa.Integer(), nullable=True),
    sa.Column('reduced_positions_change', sa.Integer(), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=True),
    sa.Column('last_total_calls', sa.Integer(), nullable=True),
    sa.Column('total_calls_change', sa.Integer(), nullable=True),
    sa.Column('total_puts', sa.Integer(), nullable=True),
    sa.Column('last_total_puts', sa.Integer(), nullable=True),
    sa.Column('total_puts_change', sa.Integer(), nullable=True),
    sa.Column('put_call_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('last_put_call_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('put_call_ratio_change', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('collected_year', sa.Integer(), nullable=True),
    sa.Column('collected_quarter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_index('ix_institutional_ownership_date', 'institutional_ownership', ['date'], unique=False)
    op.create_index('ix_institutional_ownership_year_quarter', 'institutional_ownership', ['collected_year', 'collected_quarter'], unique=False)
    op.create_table('key_metrics',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('reported_currency', sa.String(length=10), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('enterprise_value', sa.BigInteger(), nullable=True),
    sa.Column('ev_to_sales', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ev_to_operating_cash_flow', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ev_to_free_cash_flow', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ev_to_ebitda', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('net_debt_to_ebitda', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('income_quality', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('graham_number', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('graham_net_net', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('tax_burden', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('interest_burden', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('working_capital', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('invested_capital', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('return_on_assets', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('operating_return_on_assets', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('return_on_tangible_assets', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('return_on_equity', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('return_on_invested_capital', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('return_on_capital_employed', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('earnings_yield', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('free_cash_flow_yield', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('capex_to_operating_cash_flow', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('capex_to_depreciation', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('capex_to_revenue', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sales_general_and_administrative_to_revenue', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('research_and_developement_to_revenue', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('stock_based_compensation_to_revenue', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('intangibles_to_total_assets', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('average_receivables', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('average_payables', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('average_inventory', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('days_of_sales_outstanding', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('days_of_payables_outstanding', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('days_of_inventory_on_hand', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('days_of_inventory_outstanding', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('operating_cycle', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cash_conversion_cycle', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('free_cash_flow_to_equity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('free_cash_flow_to_firm', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('tangible_asset_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_current_asset_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date', 'period')
    )
    op.create_index('ix_key_metrics_symbol_date', 'key_metrics', ['symbol', 'date'], unique=False)
    op.create_table('price_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.Column('target_high', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('target_low', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('target_consensus', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('target_median', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'published_date', name='uq_price_targets_symbol_date')
    )
    op.create_index(op.f('ix_price_targets_published_date'), 'price_targets', ['published_date'], unique=False)
    op.create_index(op.f('ix_price_targets_symbol'), 'price_targets', ['symbol'], unique=False)
    op.create_index('ix_price_targets_symbol_date', 'price_targets', ['symbol', 'published_date'], unique=False)
    op.create_table('prices_daily',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('change', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('change_percent', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_index('ix_prices_daily_date_symbol', 'prices_daily', ['date'], unique=False)
    op.create_table('prices_monthly',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('change', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('change_percent', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_index(op.f('ix_prices_monthly_date'), 'prices_monthly', ['date'], unique=False)
    op.create_index('ix_prices_monthly_date_symbol', 'prices_monthly', ['date', 'symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_monthly_date_symbol', table_name='prices_monthly')
    op.drop_index(op.f('ix_prices_monthly_date'), table_name='prices_monthly')
    op.drop_table('prices_monthly')
    op.drop_index('ix_prices_daily_date_symbol', table_name='prices_daily')
    op.drop_table('prices_daily')
    op.drop_index('ix_price_targets_symbol_date', table_name='price_targets')
    op.drop_index(op.f('ix_price_targets_symbol'), table_name='price_targets')
    op.drop_index(op.f('ix_price_targets_published_date'), table_name='price_targets')
    op.drop_table('price_targets')
    op.drop_index('ix_key_metrics_symbol_date', table_name='key_metrics')
    op.drop_table('key_metrics')
    op.drop_index('ix_institutional_ownership_year_quarter', table_name='institutional_ownership')
    op.drop_index('ix_institutional_ownership_date', table_name='institutional_ownership')
    op.drop_table('institutional_ownership')
    op.drop_index(op.f('ix_insider_trading_transaction_date'), table_name='insider_trading')
    op.drop_index('ix_insider_trading_symbol_transaction_date', table_name='insider_trading')
    op.drop_index('ix_insider_trading_symbol_filing_date', table_name='insider_trading')
    op.drop_index(op.f('ix_insider_trading_symbol'), table_name='insider_trading')
    op.drop_index(op.f('ix_insider_trading_filing_date'), table_name='insider_trading')
    op.drop_table('insider_trading')
    op.drop_index('ix_insider_statistics_symbol_year_quarter', table_name='insider_statistics')
    op.drop_index(op.f('ix_insider_statistics_cik'), table_name='insider_statistics')
    op.drop_table('insider_statistics')
    op.drop_index('ix_income_statements_symbol_date', table_name='income_statements')
    op.drop_index('ix_income_statements_fiscal_year', table_name='income_statements')
    op.drop_table('income_statements')
    op.drop_index('ix_financial_ratios_symbol_date', table_name='financial_ratios')
    op.drop_index('ix_financial_ratios_fiscal_year', table_name='financial_ratios')
    op.drop_table('financial_ratios')
    op.drop_index('ix_enterprise_values_symbol_date', table_name='enterprise_values')
    op.drop_table('enterprise_values')
    op.drop_index('ix_employee_history_symbol_period', table_name='employee_history')
    op.drop_table('employee_history')
    op.drop_index('ix_cash_flows_symbol_date', table_name='cash_flows')
    op.drop_index('ix_cash_flows_fiscal_year', table_name='cash_flows')
    op.drop_table('cash_flows')
    op.drop_index('ix_balance_sheets_symbol_date', table_name='balance_sheets')
    op.drop_index('ix_balance_sheets_fiscal_year', table_name='balance_sheets')
    op.drop_table('balance_sheets')
    op.drop_index('ix_analyst_estimates_symbol_date', table_name='analyst_estimates')
    op.drop_table('analyst_estimates')
    op.drop_index('ix_update_tracking_table_symbol', table_name='table_update_tracking')
    op.drop_index('ix_update_tracking_next_due', table_name='table_update_tracking')
    op.drop_index(op.f('ix_table_update_tracking_table_name'), table_name='table_update_tracking')
    op.drop_index(op.f('ix_table_update_tracking_symbol'), table_name='table_update_tracking')
    op.drop_table('table_update_tracking')
    op.drop_index('ix_economic_indicators_name_date', table_name='economic_indicators')
    op.drop_index('ix_economic_indicators_date', table_name='economic_indicators')
    op.drop_table('economic_indicators')
    op.drop_index(op.f('ix_data_collection_log_job_name'), table_name='data_collection_log')
    op.drop_index('ix_collection_log_status', table_name='data_collection_log')
    op.drop_index('ix_collection_log_job_start', table_name='data_collection_log')
    op.drop_table('data_collection_log')
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.drop_index(op.f('ix_companies_sector'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
