"""add key metrics ttm bulk table

Revision ID: 6eab4c30b690
Revises: b6e077c05755
Create Date: 2025-11-13 21:46:54.500827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eab4c30b690'
down_revision: Union[str, Sequence[str], None] = 'b6e077c05755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_metrics_ttm_bulk',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('enterprise_value_ttm', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ev_to_sales_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('ev_to_operating_cash_flow_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('ev_to_free_cash_flow_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('ev_to_ebitda_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('net_debt_to_ebitda_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('current_ratio_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('income_quality_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('graham_number_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('graham_net_net_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('tax_burden_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('interest_burden_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('working_capital_ttm', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('invested_capital_ttm', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('return_on_assets_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('operating_return_on_assets_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('return_on_tangible_assets_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('return_on_equity_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('return_on_invested_capital_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('return_on_capital_employed_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('earnings_yield_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('free_cash_flow_yield_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('capex_to_operating_cash_flow_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('capex_to_depreciation_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('capex_to_revenue_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('sales_general_and_administrative_to_revenue_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('research_and_developement_to_revenue_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('stock_based_compensation_to_revenue_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('intangibles_to_total_assets_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('average_receivables_ttm', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('average_payables_ttm', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('average_inventory_ttm', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('days_of_sales_outstanding_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('days_of_payables_outstanding_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('days_of_inventory_outstanding_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('operating_cycle_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('cash_conversion_cycle_ttm', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('free_cash_flow_to_equity_ttm', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('free_cash_flow_to_firm_ttm', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('tangible_asset_value_ttm', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_current_asset_value_ttm', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_key_metrics_ttm_bulk_symbol'), 'key_metrics_ttm_bulk', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_key_metrics_ttm_bulk_symbol'), table_name='key_metrics_ttm_bulk')
    op.drop_table('key_metrics_ttm_bulk')
    # ### end Alembic commands ###
