"""Add BLS LN (Labor Force Statistics from CPS) tables

Revision ID: 7db74d2b38d3
Revises: 44c313f1d260
Create Date: 2025-11-16 16:36:57.019537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db74d2b38d3'
down_revision: Union[str, Sequence[str], None] = '44c313f1d260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_ln_absn',
    sa.Column('absn_code', sa.String(length=5), nullable=False),
    sa.Column('absn_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('absn_code')
    )
    op.create_table('bls_ln_activity',
    sa.Column('activity_code', sa.String(length=5), nullable=False),
    sa.Column('activity_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('activity_code')
    )
    op.create_table('bls_ln_ages',
    sa.Column('ages_code', sa.String(length=5), nullable=False),
    sa.Column('ages_text', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ages_code')
    )
    op.create_table('bls_ln_born',
    sa.Column('born_code', sa.String(length=5), nullable=False),
    sa.Column('born_text', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('born_code')
    )
    op.create_table('bls_ln_cert',
    sa.Column('cert_code', sa.String(length=5), nullable=False),
    sa.Column('cert_text', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cert_code')
    )
    op.create_table('bls_ln_chld',
    sa.Column('chld_code', sa.String(length=5), nullable=False),
    sa.Column('chld_text', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chld_code')
    )
    op.create_table('bls_ln_class',
    sa.Column('class_code', sa.String(length=5), nullable=False),
    sa.Column('class_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('class_code')
    )
    op.create_table('bls_ln_disa',
    sa.Column('disa_code', sa.String(length=5), nullable=False),
    sa.Column('disa_text', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('disa_code')
    )
    op.create_table('bls_ln_duration',
    sa.Column('duration_code', sa.String(length=5), nullable=False),
    sa.Column('duration_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('duration_code')
    )
    op.create_table('bls_ln_education',
    sa.Column('education_code', sa.String(length=5), nullable=False),
    sa.Column('education_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('education_code')
    )
    op.create_table('bls_ln_entr',
    sa.Column('entr_code', sa.String(length=5), nullable=False),
    sa.Column('entr_text', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('entr_code')
    )
    op.create_table('bls_ln_expr',
    sa.Column('expr_code', sa.String(length=5), nullable=False),
    sa.Column('expr_text', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('expr_code')
    )
    op.create_table('bls_ln_hheader',
    sa.Column('hheader_code', sa.String(length=5), nullable=False),
    sa.Column('hheader_text', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('hheader_code')
    )
    op.create_table('bls_ln_hour',
    sa.Column('hour_code', sa.String(length=5), nullable=False),
    sa.Column('hour_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('hour_code')
    )
    op.create_table('bls_ln_indy',
    sa.Column('indy_code', sa.String(length=10), nullable=False),
    sa.Column('indy_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('indy_code')
    )
    op.create_table('bls_ln_jdes',
    sa.Column('jdes_code', sa.String(length=5), nullable=False),
    sa.Column('jdes_text', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jdes_code')
    )
    op.create_table('bls_ln_lfst',
    sa.Column('lfst_code', sa.String(length=5), nullable=False),
    sa.Column('lfst_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('lfst_code')
    )
    op.create_table('bls_ln_look',
    sa.Column('look_code', sa.String(length=5), nullable=False),
    sa.Column('look_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('look_code')
    )
    op.create_table('bls_ln_mari',
    sa.Column('mari_code', sa.String(length=5), nullable=False),
    sa.Column('mari_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('mari_code')
    )
    op.create_table('bls_ln_mjhs',
    sa.Column('mjhs_code', sa.String(length=5), nullable=False),
    sa.Column('mjhs_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('mjhs_code')
    )
    op.create_table('bls_ln_occupation',
    sa.Column('occupation_code', sa.String(length=10), nullable=False),
    sa.Column('occupation_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('occupation_code')
    )
    op.create_table('bls_ln_orig',
    sa.Column('orig_code', sa.String(length=5), nullable=False),
    sa.Column('orig_text', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('orig_code')
    )
    op.create_table('bls_ln_pcts',
    sa.Column('pcts_code', sa.String(length=5), nullable=False),
    sa.Column('pcts_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pcts_code')
    )
    op.create_table('bls_ln_periodicity',
    sa.Column('periodicity_code', sa.String(length=5), nullable=False),
    sa.Column('periodicity_text', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('periodicity_code')
    )
    op.create_table('bls_ln_race',
    sa.Column('race_code', sa.String(length=5), nullable=False),
    sa.Column('race_text', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('race_code')
    )
    op.create_table('bls_ln_rjnw',
    sa.Column('rjnw_code', sa.String(length=5), nullable=False),
    sa.Column('rjnw_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rjnw_code')
    )
    op.create_table('bls_ln_rnlf',
    sa.Column('rnlf_code', sa.String(length=5), nullable=False),
    sa.Column('rnlf_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rnlf_code')
    )
    op.create_table('bls_ln_rwns',
    sa.Column('rwns_code', sa.String(length=5), nullable=False),
    sa.Column('rwns_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rwns_code')
    )
    op.create_table('bls_ln_seek',
    sa.Column('seek_code', sa.String(length=5), nullable=False),
    sa.Column('seek_text', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('seek_code')
    )
    op.create_table('bls_ln_sexs',
    sa.Column('sexs_code', sa.String(length=5), nullable=False),
    sa.Column('sexs_text', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sexs_code')
    )
    op.create_table('bls_ln_tdat',
    sa.Column('tdat_code', sa.String(length=5), nullable=False),
    sa.Column('tdat_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tdat_code')
    )
    op.create_table('bls_ln_tlwk',
    sa.Column('tlwk_code', sa.String(length=5), nullable=False),
    sa.Column('tlwk_text', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tlwk_code')
    )
    op.create_table('bls_ln_vets',
    sa.Column('vets_code', sa.String(length=5), nullable=False),
    sa.Column('vets_text', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('vets_code')
    )
    op.create_table('bls_ln_wkst',
    sa.Column('wkst_code', sa.String(length=5), nullable=False),
    sa.Column('wkst_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('wkst_code')
    )
    op.create_table('bls_ln_series',
    sa.Column('series_id', sa.String(length=20), nullable=False),
    sa.Column('lfst_code', sa.String(length=5), nullable=True),
    sa.Column('periodicity_code', sa.String(length=5), nullable=True),
    sa.Column('absn_code', sa.String(length=5), nullable=True),
    sa.Column('activity_code', sa.String(length=5), nullable=True),
    sa.Column('ages_code', sa.String(length=5), nullable=True),
    sa.Column('cert_code', sa.String(length=5), nullable=True),
    sa.Column('class_code', sa.String(length=5), nullable=True),
    sa.Column('duration_code', sa.String(length=5), nullable=True),
    sa.Column('education_code', sa.String(length=5), nullable=True),
    sa.Column('entr_code', sa.String(length=5), nullable=True),
    sa.Column('expr_code', sa.String(length=5), nullable=True),
    sa.Column('hheader_code', sa.String(length=5), nullable=True),
    sa.Column('hour_code', sa.String(length=5), nullable=True),
    sa.Column('indy_code', sa.String(length=10), nullable=True),
    sa.Column('jdes_code', sa.String(length=5), nullable=True),
    sa.Column('look_code', sa.String(length=5), nullable=True),
    sa.Column('mari_code', sa.String(length=5), nullable=True),
    sa.Column('mjhs_code', sa.String(length=5), nullable=True),
    sa.Column('occupation_code', sa.String(length=10), nullable=True),
    sa.Column('orig_code', sa.String(length=5), nullable=True),
    sa.Column('pcts_code', sa.String(length=5), nullable=True),
    sa.Column('race_code', sa.String(length=5), nullable=True),
    sa.Column('rjnw_code', sa.String(length=5), nullable=True),
    sa.Column('rnlf_code', sa.String(length=5), nullable=True),
    sa.Column('rwns_code', sa.String(length=5), nullable=True),
    sa.Column('seek_code', sa.String(length=5), nullable=True),
    sa.Column('sexs_code', sa.String(length=5), nullable=True),
    sa.Column('tdat_code', sa.String(length=5), nullable=True),
    sa.Column('vets_code', sa.String(length=5), nullable=True),
    sa.Column('wkst_code', sa.String(length=5), nullable=True),
    sa.Column('born_code', sa.String(length=5), nullable=True),
    sa.Column('chld_code', sa.String(length=5), nullable=True),
    sa.Column('disa_code', sa.String(length=5), nullable=True),
    sa.Column('tlwk_code', sa.String(length=5), nullable=True),
    sa.Column('seasonal', sa.String(length=1), nullable=True),
    sa.Column('series_title', sa.Text(), nullable=False),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('begin_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_period', sa.String(length=5), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_period', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['absn_code'], ['bls_ln_absn.absn_code'], ),
    sa.ForeignKeyConstraint(['activity_code'], ['bls_ln_activity.activity_code'], ),
    sa.ForeignKeyConstraint(['ages_code'], ['bls_ln_ages.ages_code'], ),
    sa.ForeignKeyConstraint(['born_code'], ['bls_ln_born.born_code'], ),
    sa.ForeignKeyConstraint(['cert_code'], ['bls_ln_cert.cert_code'], ),
    sa.ForeignKeyConstraint(['chld_code'], ['bls_ln_chld.chld_code'], ),
    sa.ForeignKeyConstraint(['class_code'], ['bls_ln_class.class_code'], ),
    sa.ForeignKeyConstraint(['disa_code'], ['bls_ln_disa.disa_code'], ),
    sa.ForeignKeyConstraint(['duration_code'], ['bls_ln_duration.duration_code'], ),
    sa.ForeignKeyConstraint(['education_code'], ['bls_ln_education.education_code'], ),
    sa.ForeignKeyConstraint(['entr_code'], ['bls_ln_entr.entr_code'], ),
    sa.ForeignKeyConstraint(['expr_code'], ['bls_ln_expr.expr_code'], ),
    sa.ForeignKeyConstraint(['hheader_code'], ['bls_ln_hheader.hheader_code'], ),
    sa.ForeignKeyConstraint(['hour_code'], ['bls_ln_hour.hour_code'], ),
    sa.ForeignKeyConstraint(['indy_code'], ['bls_ln_indy.indy_code'], ),
    sa.ForeignKeyConstraint(['jdes_code'], ['bls_ln_jdes.jdes_code'], ),
    sa.ForeignKeyConstraint(['lfst_code'], ['bls_ln_lfst.lfst_code'], ),
    sa.ForeignKeyConstraint(['look_code'], ['bls_ln_look.look_code'], ),
    sa.ForeignKeyConstraint(['mari_code'], ['bls_ln_mari.mari_code'], ),
    sa.ForeignKeyConstraint(['mjhs_code'], ['bls_ln_mjhs.mjhs_code'], ),
    sa.ForeignKeyConstraint(['occupation_code'], ['bls_ln_occupation.occupation_code'], ),
    sa.ForeignKeyConstraint(['orig_code'], ['bls_ln_orig.orig_code'], ),
    sa.ForeignKeyConstraint(['pcts_code'], ['bls_ln_pcts.pcts_code'], ),
    sa.ForeignKeyConstraint(['periodicity_code'], ['bls_ln_periodicity.periodicity_code'], ),
    sa.ForeignKeyConstraint(['race_code'], ['bls_ln_race.race_code'], ),
    sa.ForeignKeyConstraint(['rjnw_code'], ['bls_ln_rjnw.rjnw_code'], ),
    sa.ForeignKeyConstraint(['rnlf_code'], ['bls_ln_rnlf.rnlf_code'], ),
    sa.ForeignKeyConstraint(['rwns_code'], ['bls_ln_rwns.rwns_code'], ),
    sa.ForeignKeyConstraint(['seek_code'], ['bls_ln_seek.seek_code'], ),
    sa.ForeignKeyConstraint(['sexs_code'], ['bls_ln_sexs.sexs_code'], ),
    sa.ForeignKeyConstraint(['tdat_code'], ['bls_ln_tdat.tdat_code'], ),
    sa.ForeignKeyConstraint(['tlwk_code'], ['bls_ln_tlwk.tlwk_code'], ),
    sa.ForeignKeyConstraint(['vets_code'], ['bls_ln_vets.vets_code'], ),
    sa.ForeignKeyConstraint(['wkst_code'], ['bls_ln_wkst.wkst_code'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index('ix_bls_ln_series_active', 'bls_ln_series', ['is_active'], unique=False)
    op.create_index('ix_bls_ln_series_ages', 'bls_ln_series', ['ages_code'], unique=False)
    op.create_index('ix_bls_ln_series_education', 'bls_ln_series', ['education_code'], unique=False)
    op.create_index('ix_bls_ln_series_industry', 'bls_ln_series', ['indy_code'], unique=False)
    op.create_index('ix_bls_ln_series_lfst', 'bls_ln_series', ['lfst_code'], unique=False)
    op.create_index('ix_bls_ln_series_occupation', 'bls_ln_series', ['occupation_code'], unique=False)
    op.create_index('ix_bls_ln_series_race', 'bls_ln_series', ['race_code'], unique=False)
    op.create_index('ix_bls_ln_series_seasonal', 'bls_ln_series', ['seasonal'], unique=False)
    op.create_index('ix_bls_ln_series_sexs', 'bls_ln_series', ['sexs_code'], unique=False)
    op.create_table('bls_ln_data',
    sa.Column('series_id', sa.String(length=20), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=1), nullable=True),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['bls_ln_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'year', 'period')
    )
    op.create_index('ix_bls_ln_data_series_year', 'bls_ln_data', ['series_id', 'year'], unique=False)
    op.create_index('ix_bls_ln_data_year_period', 'bls_ln_data', ['year', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bls_ln_data_year_period', table_name='bls_ln_data')
    op.drop_index('ix_bls_ln_data_series_year', table_name='bls_ln_data')
    op.drop_table('bls_ln_data')
    op.drop_index('ix_bls_ln_series_sexs', table_name='bls_ln_series')
    op.drop_index('ix_bls_ln_series_seasonal', table_name='bls_ln_series')
    op.drop_index('ix_bls_ln_series_race', table_name='bls_ln_series')
    op.drop_index('ix_bls_ln_series_occupation', table_name='bls_ln_series')
    op.drop_index('ix_bls_ln_series_lfst', table_name='bls_ln_series')
    op.drop_index('ix_bls_ln_series_industry', table_name='bls_ln_series')
    op.drop_index('ix_bls_ln_series_education', table_name='bls_ln_series')
    op.drop_index('ix_bls_ln_series_ages', table_name='bls_ln_series')
    op.drop_index('ix_bls_ln_series_active', table_name='bls_ln_series')
    op.drop_table('bls_ln_series')
    op.drop_table('bls_ln_wkst')
    op.drop_table('bls_ln_vets')
    op.drop_table('bls_ln_tlwk')
    op.drop_table('bls_ln_tdat')
    op.drop_table('bls_ln_sexs')
    op.drop_table('bls_ln_seek')
    op.drop_table('bls_ln_rwns')
    op.drop_table('bls_ln_rnlf')
    op.drop_table('bls_ln_rjnw')
    op.drop_table('bls_ln_race')
    op.drop_table('bls_ln_periodicity')
    op.drop_table('bls_ln_pcts')
    op.drop_table('bls_ln_orig')
    op.drop_table('bls_ln_occupation')
    op.drop_table('bls_ln_mjhs')
    op.drop_table('bls_ln_mari')
    op.drop_table('bls_ln_look')
    op.drop_table('bls_ln_lfst')
    op.drop_table('bls_ln_jdes')
    op.drop_table('bls_ln_indy')
    op.drop_table('bls_ln_hour')
    op.drop_table('bls_ln_hheader')
    op.drop_table('bls_ln_expr')
    op.drop_table('bls_ln_entr')
    op.drop_table('bls_ln_education')
    op.drop_table('bls_ln_duration')
    op.drop_table('bls_ln_disa')
    op.drop_table('bls_ln_class')
    op.drop_table('bls_ln_chld')
    op.drop_table('bls_ln_cert')
    op.drop_table('bls_ln_born')
    op.drop_table('bls_ln_ages')
    op.drop_table('bls_ln_activity')
    op.drop_table('bls_ln_absn')
    # ### end Alembic commands ###
