"""add bls_su_chained_cpi_u_tables

Revision ID: 85443bfe6cec
Revises: 3a87ad1076b8
Create Date: 2025-11-16 20:51:47.215894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85443bfe6cec'
down_revision: Union[str, Sequence[str], None] = '3a87ad1076b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_su_areas',
    sa.Column('area_code', sa.String(length=10), nullable=False),
    sa.Column('area_name', sa.String(length=255), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('area_code')
    )
    op.create_index('ix_bls_su_areas_display_level', 'bls_su_areas', ['display_level'], unique=False)
    op.create_index('ix_bls_su_areas_selectable', 'bls_su_areas', ['selectable'], unique=False)
    op.create_table('bls_su_items',
    sa.Column('item_code', sa.String(length=20), nullable=False),
    sa.Column('item_name', sa.String(length=500), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('item_code')
    )
    op.create_index('ix_bls_su_items_display_level', 'bls_su_items', ['display_level'], unique=False)
    op.create_index('ix_bls_su_items_selectable', 'bls_su_items', ['selectable'], unique=False)
    op.create_table('bls_su_series',
    sa.Column('series_id', sa.String(length=20), nullable=False),
    sa.Column('area_code', sa.String(length=10), nullable=True),
    sa.Column('item_code', sa.String(length=20), nullable=True),
    sa.Column('seasonal_code', sa.String(length=1), nullable=True),
    sa.Column('periodicity_code', sa.String(length=5), nullable=True),
    sa.Column('base_code', sa.String(length=10), nullable=True),
    sa.Column('base_period', sa.String(length=50), nullable=True),
    sa.Column('series_title', sa.Text(), nullable=False),
    sa.Column('footnote_codes', sa.String(length=50), nullable=True),
    sa.Column('begin_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_period', sa.String(length=5), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_period', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_code'], ['bls_su_areas.area_code'], ),
    sa.ForeignKeyConstraint(['item_code'], ['bls_su_items.item_code'], ),
    sa.ForeignKeyConstraint(['periodicity_code'], ['bls_periodicity.periodicity_code'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index('ix_bls_su_series_active', 'bls_su_series', ['is_active'], unique=False)
    op.create_index('ix_bls_su_series_area', 'bls_su_series', ['area_code'], unique=False)
    op.create_index('ix_bls_su_series_item', 'bls_su_series', ['item_code'], unique=False)
    op.create_index('ix_bls_su_series_seasonal', 'bls_su_series', ['seasonal_code'], unique=False)
    op.create_table('bls_su_data',
    sa.Column('series_id', sa.String(length=20), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('footnote_codes', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['bls_su_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'year', 'period')
    )
    op.create_index('ix_bls_su_data_series_year', 'bls_su_data', ['series_id', 'year'], unique=False)
    op.create_index('ix_bls_su_data_year_period', 'bls_su_data', ['year', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bls_su_data_year_period', table_name='bls_su_data')
    op.drop_index('ix_bls_su_data_series_year', table_name='bls_su_data')
    op.drop_table('bls_su_data')
    op.drop_index('ix_bls_su_series_seasonal', table_name='bls_su_series')
    op.drop_index('ix_bls_su_series_item', table_name='bls_su_series')
    op.drop_index('ix_bls_su_series_area', table_name='bls_su_series')
    op.drop_index('ix_bls_su_series_active', table_name='bls_su_series')
    op.drop_table('bls_su_series')
    op.drop_index('ix_bls_su_items_selectable', table_name='bls_su_items')
    op.drop_index('ix_bls_su_items_display_level', table_name='bls_su_items')
    op.drop_table('bls_su_items')
    op.drop_index('ix_bls_su_areas_selectable', table_name='bls_su_areas')
    op.drop_index('ix_bls_su_areas_display_level', table_name='bls_su_areas')
    op.drop_table('bls_su_areas')
    # ### end Alembic commands ###
