"""add BEA tables

Revision ID: 946a41c247c0
Revises: 0adf07805582
Create Date: 2025-11-26 18:03:30.841089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946a41c247c0'
down_revision: Union[str, Sequence[str], None] = '0adf07805582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bea_api_usage_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('usage_minute', sa.DateTime(), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.Column('data_bytes', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(length=50), nullable=True),
    sa.Column('method_name', sa.String(length=50), nullable=True),
    sa.Column('http_status', sa.SmallInteger(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('script_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_bea_api_usage_dataset', 'bea_api_usage_log', ['dataset_name'], unique=False)
    op.create_index('ix_bea_api_usage_date_minute', 'bea_api_usage_log', ['usage_date', 'usage_minute'], unique=False)
    op.create_index(op.f('ix_bea_api_usage_log_dataset_name'), 'bea_api_usage_log', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_bea_api_usage_log_usage_date'), 'bea_api_usage_log', ['usage_date'], unique=False)
    op.create_index(op.f('ix_bea_api_usage_log_usage_minute'), 'bea_api_usage_log', ['usage_minute'], unique=False)
    op.create_table('bea_collection_runs',
    sa.Column('run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_name', sa.String(length=50), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tables_processed', sa.Integer(), nullable=False),
    sa.Column('series_processed', sa.Integer(), nullable=False),
    sa.Column('data_points_inserted', sa.Integer(), nullable=False),
    sa.Column('data_points_updated', sa.Integer(), nullable=False),
    sa.Column('api_requests_made', sa.Integer(), nullable=False),
    sa.Column('start_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('tables_filter', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_bea_collection_runs_dataset_name'), 'bea_collection_runs', ['dataset_name'], unique=False)
    op.create_index('ix_bea_runs_dataset_status', 'bea_collection_runs', ['dataset_name', 'status'], unique=False)
    op.create_index('ix_bea_runs_started', 'bea_collection_runs', ['started_at'], unique=False)
    op.create_table('bea_dataset_freshness',
    sa.Column('dataset_name', sa.String(length=50), nullable=False),
    sa.Column('latest_data_year', sa.SmallInteger(), nullable=True),
    sa.Column('latest_data_period', sa.String(length=10), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_bea_update_detected', sa.DateTime(), nullable=True),
    sa.Column('needs_update', sa.Boolean(), nullable=False),
    sa.Column('update_in_progress', sa.Boolean(), nullable=False),
    sa.Column('last_update_started', sa.DateTime(), nullable=True),
    sa.Column('last_update_completed', sa.DateTime(), nullable=True),
    sa.Column('tables_count', sa.Integer(), nullable=False),
    sa.Column('series_count', sa.Integer(), nullable=False),
    sa.Column('data_points_count', sa.Integer(), nullable=False),
    sa.Column('total_checks', sa.Integer(), nullable=False),
    sa.Column('total_updates_detected', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('dataset_name')
    )
    op.create_index(op.f('ix_bea_dataset_freshness_last_checked_at'), 'bea_dataset_freshness', ['last_checked_at'], unique=False)
    op.create_index(op.f('ix_bea_dataset_freshness_needs_update'), 'bea_dataset_freshness', ['needs_update'], unique=False)
    op.create_table('bea_datasets',
    sa.Column('dataset_name', sa.String(length=50), nullable=False),
    sa.Column('dataset_description', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('doc_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('dataset_name')
    )
    op.create_table('bea_gdp_summary',
    sa.Column('geo_fips', sa.String(length=10), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('quarter', sa.String(length=5), nullable=True),
    sa.Column('gdp_current', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('gdp_real', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('gdp_percent_change', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('gdp_per_capita', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('source_table', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('geo_fips', 'year')
    )
    op.create_index('ix_bea_gdp_summary_geo', 'bea_gdp_summary', ['geo_fips'], unique=False)
    op.create_index('ix_bea_gdp_summary_geo_year', 'bea_gdp_summary', ['geo_fips', 'year'], unique=False)
    op.create_index('ix_bea_gdp_summary_year', 'bea_gdp_summary', ['year'], unique=False)
    op.create_table('bea_nipa_tables',
    sa.Column('table_name', sa.String(length=20), nullable=False),
    sa.Column('table_description', sa.Text(), nullable=False),
    sa.Column('has_annual', sa.Boolean(), nullable=True),
    sa.Column('has_quarterly', sa.Boolean(), nullable=True),
    sa.Column('has_monthly', sa.Boolean(), nullable=True),
    sa.Column('first_year', sa.SmallInteger(), nullable=True),
    sa.Column('last_year', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('table_name')
    )
    op.create_index('ix_bea_nipa_tables_active', 'bea_nipa_tables', ['is_active'], unique=False)
    op.create_table('bea_personal_income_summary',
    sa.Column('geo_fips', sa.String(length=10), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('quarter', sa.String(length=5), nullable=True),
    sa.Column('personal_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('per_capita_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('wages_salaries', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('supplements_to_wages', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('proprietors_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('dividends_interest_rent', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('personal_current_transfer_receipts', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('source_table', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('geo_fips', 'year')
    )
    op.create_index('ix_bea_pi_summary_geo', 'bea_personal_income_summary', ['geo_fips'], unique=False)
    op.create_index('ix_bea_pi_summary_geo_year', 'bea_personal_income_summary', ['geo_fips', 'year'], unique=False)
    op.create_index('ix_bea_pi_summary_year', 'bea_personal_income_summary', ['year'], unique=False)
    op.create_table('bea_regional_geo_fips',
    sa.Column('geo_fips', sa.String(length=10), nullable=False),
    sa.Column('geo_name', sa.String(length=255), nullable=False),
    sa.Column('geo_type', sa.String(length=50), nullable=True),
    sa.Column('parent_fips', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('geo_fips')
    )
    op.create_index('ix_bea_regional_geo_fips_parent', 'bea_regional_geo_fips', ['parent_fips'], unique=False)
    op.create_index('ix_bea_regional_geo_fips_type', 'bea_regional_geo_fips', ['geo_type'], unique=False)
    op.create_table('bea_regional_tables',
    sa.Column('table_name', sa.String(length=20), nullable=False),
    sa.Column('table_description', sa.Text(), nullable=False),
    sa.Column('geo_scope', sa.String(length=50), nullable=True),
    sa.Column('first_year', sa.SmallInteger(), nullable=True),
    sa.Column('last_year', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('table_name')
    )
    op.create_index('ix_bea_regional_tables_active', 'bea_regional_tables', ['is_active'], unique=False)
    op.create_index('ix_bea_regional_tables_scope', 'bea_regional_tables', ['geo_scope'], unique=False)
    op.create_table('bea_release_schedule',
    sa.Column('schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_name', sa.String(length=50), nullable=False),
    sa.Column('release_name', sa.String(length=100), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('release_time', sa.String(length=10), nullable=True),
    sa.Column('data_period', sa.String(length=20), nullable=True),
    sa.Column('tables_affected', sa.Text(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index(op.f('ix_bea_release_schedule_dataset_name'), 'bea_release_schedule', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_bea_release_schedule_release_date'), 'bea_release_schedule', ['release_date'], unique=False)
    op.create_index('ix_bea_schedule_dataset_date', 'bea_release_schedule', ['dataset_name', 'release_date'], unique=False)
    op.create_index('ix_bea_schedule_date', 'bea_release_schedule', ['release_date'], unique=False)
    op.create_table('bea_sentinel_series',
    sa.Column('dataset_name', sa.String(length=50), nullable=False),
    sa.Column('sentinel_id', sa.String(length=100), nullable=False),
    sa.Column('sentinel_order', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=20), nullable=False),
    sa.Column('line_code', sa.SmallInteger(), nullable=True),
    sa.Column('geo_fips', sa.String(length=10), nullable=True),
    sa.Column('series_code', sa.String(length=50), nullable=True),
    sa.Column('selection_reason', sa.String(length=100), nullable=True),
    sa.Column('last_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('last_year', sa.SmallInteger(), nullable=True),
    sa.Column('last_period', sa.String(length=10), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(), nullable=True),
    sa.Column('check_count', sa.Integer(), nullable=False),
    sa.Column('change_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('dataset_name', 'sentinel_id')
    )
    op.create_index('ix_bea_sentinel_dataset', 'bea_sentinel_series', ['dataset_name'], unique=False)
    op.create_index('ix_bea_sentinel_order', 'bea_sentinel_series', ['dataset_name', 'sentinel_order'], unique=False)
    op.create_table('bea_table_update_status',
    sa.Column('dataset_name', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=20), nullable=False),
    sa.Column('last_data_year', sa.SmallInteger(), nullable=True),
    sa.Column('last_data_period', sa.String(length=10), nullable=True),
    sa.Column('bea_first_year', sa.SmallInteger(), nullable=True),
    sa.Column('bea_last_year', sa.SmallInteger(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('rows_in_table', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('dataset_name', 'table_name')
    )
    op.create_index('ix_bea_table_status_current', 'bea_table_update_status', ['is_current'], unique=False)
    op.create_index('ix_bea_table_status_dataset', 'bea_table_update_status', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_bea_table_update_status_is_current'), 'bea_table_update_status', ['is_current'], unique=False)
    op.create_table('bea_nipa_series',
    sa.Column('series_code', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=20), nullable=False),
    sa.Column('line_number', sa.SmallInteger(), nullable=False),
    sa.Column('line_description', sa.Text(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=True),
    sa.Column('cl_unit', sa.String(length=50), nullable=True),
    sa.Column('unit_mult', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_name'], ['bea_nipa_tables.table_name'], ),
    sa.PrimaryKeyConstraint('series_code')
    )
    op.create_index('ix_bea_nipa_series_active', 'bea_nipa_series', ['is_active'], unique=False)
    op.create_index('ix_bea_nipa_series_table_line', 'bea_nipa_series', ['table_name', 'line_number'], unique=False)
    op.create_index(op.f('ix_bea_nipa_series_table_name'), 'bea_nipa_series', ['table_name'], unique=False)
    op.create_table('bea_regional_line_codes',
    sa.Column('table_name', sa.String(length=20), nullable=False),
    sa.Column('line_code', sa.SmallInteger(), nullable=False),
    sa.Column('line_description', sa.Text(), nullable=False),
    sa.Column('cl_unit', sa.String(length=50), nullable=True),
    sa.Column('unit_mult', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_name'], ['bea_regional_tables.table_name'], ),
    sa.PrimaryKeyConstraint('table_name', 'line_code')
    )
    op.create_index('ix_bea_regional_line_codes_table', 'bea_regional_line_codes', ['table_name'], unique=False)
    op.create_table('bea_nipa_data',
    sa.Column('series_code', sa.String(length=50), nullable=False),
    sa.Column('time_period', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('note_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_code'], ['bea_nipa_series.series_code'], ),
    sa.PrimaryKeyConstraint('series_code', 'time_period')
    )
    op.create_index('ix_bea_nipa_data_period', 'bea_nipa_data', ['time_period'], unique=False)
    op.create_index('ix_bea_nipa_data_series', 'bea_nipa_data', ['series_code'], unique=False)
    op.create_table('bea_regional_data',
    sa.Column('table_name', sa.String(length=20), nullable=False),
    sa.Column('line_code', sa.SmallInteger(), nullable=False),
    sa.Column('geo_fips', sa.String(length=10), nullable=False),
    sa.Column('time_period', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('cl_unit', sa.String(length=50), nullable=True),
    sa.Column('unit_mult', sa.SmallInteger(), nullable=True),
    sa.Column('note_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['geo_fips'], ['bea_regional_geo_fips.geo_fips'], ),
    sa.ForeignKeyConstraint(['table_name', 'line_code'], ['bea_regional_line_codes.table_name', 'bea_regional_line_codes.line_code'], ),
    sa.PrimaryKeyConstraint('table_name', 'line_code', 'geo_fips', 'time_period')
    )
    op.create_index('ix_bea_regional_data_geo', 'bea_regional_data', ['geo_fips'], unique=False)
    op.create_index('ix_bea_regional_data_geo_period', 'bea_regional_data', ['geo_fips', 'time_period'], unique=False)
    op.create_index('ix_bea_regional_data_period', 'bea_regional_data', ['time_period'], unique=False)
    op.create_index('ix_bea_regional_data_table', 'bea_regional_data', ['table_name'], unique=False)
    op.create_index('ix_bea_regional_data_table_line', 'bea_regional_data', ['table_name', 'line_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bea_regional_data_table_line', table_name='bea_regional_data')
    op.drop_index('ix_bea_regional_data_table', table_name='bea_regional_data')
    op.drop_index('ix_bea_regional_data_period', table_name='bea_regional_data')
    op.drop_index('ix_bea_regional_data_geo_period', table_name='bea_regional_data')
    op.drop_index('ix_bea_regional_data_geo', table_name='bea_regional_data')
    op.drop_table('bea_regional_data')
    op.drop_index('ix_bea_nipa_data_series', table_name='bea_nipa_data')
    op.drop_index('ix_bea_nipa_data_period', table_name='bea_nipa_data')
    op.drop_table('bea_nipa_data')
    op.drop_index('ix_bea_regional_line_codes_table', table_name='bea_regional_line_codes')
    op.drop_table('bea_regional_line_codes')
    op.drop_index(op.f('ix_bea_nipa_series_table_name'), table_name='bea_nipa_series')
    op.drop_index('ix_bea_nipa_series_table_line', table_name='bea_nipa_series')
    op.drop_index('ix_bea_nipa_series_active', table_name='bea_nipa_series')
    op.drop_table('bea_nipa_series')
    op.drop_index(op.f('ix_bea_table_update_status_is_current'), table_name='bea_table_update_status')
    op.drop_index('ix_bea_table_status_dataset', table_name='bea_table_update_status')
    op.drop_index('ix_bea_table_status_current', table_name='bea_table_update_status')
    op.drop_table('bea_table_update_status')
    op.drop_index('ix_bea_sentinel_order', table_name='bea_sentinel_series')
    op.drop_index('ix_bea_sentinel_dataset', table_name='bea_sentinel_series')
    op.drop_table('bea_sentinel_series')
    op.drop_index('ix_bea_schedule_date', table_name='bea_release_schedule')
    op.drop_index('ix_bea_schedule_dataset_date', table_name='bea_release_schedule')
    op.drop_index(op.f('ix_bea_release_schedule_release_date'), table_name='bea_release_schedule')
    op.drop_index(op.f('ix_bea_release_schedule_dataset_name'), table_name='bea_release_schedule')
    op.drop_table('bea_release_schedule')
    op.drop_index('ix_bea_regional_tables_scope', table_name='bea_regional_tables')
    op.drop_index('ix_bea_regional_tables_active', table_name='bea_regional_tables')
    op.drop_table('bea_regional_tables')
    op.drop_index('ix_bea_regional_geo_fips_type', table_name='bea_regional_geo_fips')
    op.drop_index('ix_bea_regional_geo_fips_parent', table_name='bea_regional_geo_fips')
    op.drop_table('bea_regional_geo_fips')
    op.drop_index('ix_bea_pi_summary_year', table_name='bea_personal_income_summary')
    op.drop_index('ix_bea_pi_summary_geo_year', table_name='bea_personal_income_summary')
    op.drop_index('ix_bea_pi_summary_geo', table_name='bea_personal_income_summary')
    op.drop_table('bea_personal_income_summary')
    op.drop_index('ix_bea_nipa_tables_active', table_name='bea_nipa_tables')
    op.drop_table('bea_nipa_tables')
    op.drop_index('ix_bea_gdp_summary_year', table_name='bea_gdp_summary')
    op.drop_index('ix_bea_gdp_summary_geo_year', table_name='bea_gdp_summary')
    op.drop_index('ix_bea_gdp_summary_geo', table_name='bea_gdp_summary')
    op.drop_table('bea_gdp_summary')
    op.drop_table('bea_datasets')
    op.drop_index(op.f('ix_bea_dataset_freshness_needs_update'), table_name='bea_dataset_freshness')
    op.drop_index(op.f('ix_bea_dataset_freshness_last_checked_at'), table_name='bea_dataset_freshness')
    op.drop_table('bea_dataset_freshness')
    op.drop_index('ix_bea_runs_started', table_name='bea_collection_runs')
    op.drop_index('ix_bea_runs_dataset_status', table_name='bea_collection_runs')
    op.drop_index(op.f('ix_bea_collection_runs_dataset_name'), table_name='bea_collection_runs')
    op.drop_table('bea_collection_runs')
    op.drop_index(op.f('ix_bea_api_usage_log_usage_minute'), table_name='bea_api_usage_log')
    op.drop_index(op.f('ix_bea_api_usage_log_usage_date'), table_name='bea_api_usage_log')
    op.drop_index(op.f('ix_bea_api_usage_log_dataset_name'), table_name='bea_api_usage_log')
    op.drop_index('ix_bea_api_usage_date_minute', table_name='bea_api_usage_log')
    op.drop_index('ix_bea_api_usage_dataset', table_name='bea_api_usage_log')
    op.drop_table('bea_api_usage_log')
    # ### end Alembic commands ###
