"""Fix CE industry column sizes for publishing_status and selectable

Revision ID: 9b325269f6f9
Revises: 299241c31863
Create Date: 2025-11-15 16:30:07.191398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b325269f6f9'
down_revision: Union[str, Sequence[str], None] = '299241c31863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bls_ce_industries', 'publishing_status',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=5),
               existing_nullable=True)
    op.alter_column('bls_ce_industries', 'selectable',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=5),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bls_ce_industries', 'selectable',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
    op.alter_column('bls_ce_industries', 'publishing_status',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
    # ### end Alembic commands ###
