"""add_earnings_calendar_no_fk

Revision ID: a49c4f25c8d7
Revises: 61bf6a771bfa
Create Date: 2025-11-06 22:10:58.085826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a49c4f25c8d7'
down_revision: Union[str, Sequence[str], None] = '61bf6a771bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_calendar',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('eps_actual', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('eps_estimated', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('revenue_actual', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('revenue_estimated', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_index('ix_earnings_calendar_date', 'earnings_calendar', ['date'], unique=False)
    op.create_index(op.f('ix_earnings_calendar_symbol'), 'earnings_calendar', ['symbol'], unique=False)
    op.create_index('ix_earnings_calendar_symbol_date', 'earnings_calendar', ['symbol', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_earnings_calendar_symbol_date', table_name='earnings_calendar')
    op.drop_index(op.f('ix_earnings_calendar_symbol'), table_name='earnings_calendar')
    op.drop_index('ix_earnings_calendar_date', table_name='earnings_calendar')
    op.drop_table('earnings_calendar')
    # ### end Alembic commands ###
