"""replace_prices_monthly_with_adjusted_prices

Revision ID: a990dd38f509
Revises: 4a29b6231995
Create Date: 2025-11-09 16:09:47.521733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a990dd38f509'
down_revision: Union[str, Sequence[str], None] = '4a29b6231995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices_monthly', sa.Column('adj_open', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('prices_monthly', sa.Column('adj_high', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('prices_monthly', sa.Column('adj_low', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('prices_monthly', sa.Column('adj_close', sa.Numeric(precision=20, scale=4), nullable=True))
    op.drop_column('prices_monthly', 'open')
    op.drop_column('prices_monthly', 'change_percent')
    op.drop_column('prices_monthly', 'vwap')
    op.drop_column('prices_monthly', 'low')
    op.drop_column('prices_monthly', 'change')
    op.drop_column('prices_monthly', 'high')
    op.drop_column('prices_monthly', 'close')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices_monthly', sa.Column('close', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
    op.add_column('prices_monthly', sa.Column('high', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
    op.add_column('prices_monthly', sa.Column('change', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
    op.add_column('prices_monthly', sa.Column('low', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
    op.add_column('prices_monthly', sa.Column('vwap', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
    op.add_column('prices_monthly', sa.Column('change_percent', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=True))
    op.add_column('prices_monthly', sa.Column('open', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
    op.drop_column('prices_monthly', 'adj_close')
    op.drop_column('prices_monthly', 'adj_low')
    op.drop_column('prices_monthly', 'adj_high')
    op.drop_column('prices_monthly', 'adj_open')
    # ### end Alembic commands ###
