"""increase_numeric_precision

Revision ID: b6dcd324a613
Revises: 63ccfe5a2ad8
Create Date: 2025-11-04 16:12:07.722389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6dcd324a613'
down_revision: Union[str, Sequence[str], None] = '63ccfe5a2ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyst_estimates', 'eps_avg',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('analyst_estimates', 'eps_high',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('analyst_estimates', 'eps_low',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('companies', 'beta',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('companies', 'last_dividend',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('companies', 'change_percentage',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'gross_profit_margin',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'ebit_margin',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'ebitda_margin',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'operating_profit_margin',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'pretax_profit_margin',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'continuous_operations_profit_margin',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'net_profit_margin',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'bottom_line_profit_margin',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'receivables_turnover',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'payables_turnover',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'inventory_turnover',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'fixed_asset_turnover',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'asset_turnover',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'current_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'quick_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'solvency_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'cash_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'price_to_earnings_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'price_to_earnings_growth_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'forward_price_to_earnings_growth_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'price_to_book_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'price_to_sales_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'price_to_free_cash_flow_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'price_to_operating_cash_flow_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'debt_to_assets_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'debt_to_equity_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'debt_to_capital_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'long_term_debt_to_capital_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'financial_leverage_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'working_capital_turnover_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'operating_cash_flow_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'operating_cash_flow_sales_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'free_cash_flow_operating_cash_flow_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'debt_service_coverage_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'interest_coverage_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'short_term_operating_cash_flow_coverage_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'operating_cash_flow_coverage_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'capital_expenditure_coverage_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'dividend_paid_and_capex_coverage_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'dividend_payout_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'dividend_yield',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'dividend_yield_percentage',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'net_income_per_ebt',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'ebt_per_ebit',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'price_to_fair_value',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'debt_to_market_cap',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'effective_tax_rate',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'enterprise_value_multiple',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('income_statements', 'gross_profit_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('income_statements', 'ebitda_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('income_statements', 'operating_income_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('income_statements', 'income_before_tax_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('income_statements', 'net_income_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('insider_statistics', 'acquired_disposed_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('institutional_ownership', 'ownership_percent',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('institutional_ownership', 'last_ownership_percent',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('institutional_ownership', 'ownership_percent_change',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('institutional_ownership', 'put_call_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('institutional_ownership', 'last_put_call_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('institutional_ownership', 'put_call_ratio_change',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'ev_to_sales',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics', 'ev_to_operating_cash_flow',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics', 'ev_to_free_cash_flow',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics', 'ev_to_ebitda',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics', 'net_debt_to_ebitda',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics', 'current_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics', 'income_quality',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'tax_burden',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'interest_burden',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'return_on_assets',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'operating_return_on_assets',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'return_on_tangible_assets',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'return_on_equity',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'return_on_invested_capital',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'return_on_capital_employed',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'earnings_yield',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'free_cash_flow_yield',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'capex_to_operating_cash_flow',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'capex_to_depreciation',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics', 'capex_to_revenue',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'sales_general_and_administrative_to_revenue',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'research_and_developement_to_revenue',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'stock_based_compensation_to_revenue',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'intangibles_to_total_assets',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'days_of_sales_outstanding',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('key_metrics', 'days_of_payables_outstanding',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('key_metrics', 'days_of_inventory_on_hand',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('key_metrics', 'days_of_inventory_outstanding',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('key_metrics', 'operating_cycle',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('key_metrics', 'cash_conversion_cycle',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('prices_daily', 'change_percent',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('prices_monthly', 'change_percent',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices_monthly', 'change_percent',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('prices_daily', 'change_percent',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'cash_conversion_cycle',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('key_metrics', 'operating_cycle',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('key_metrics', 'days_of_inventory_outstanding',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('key_metrics', 'days_of_inventory_on_hand',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('key_metrics', 'days_of_payables_outstanding',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('key_metrics', 'days_of_sales_outstanding',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('key_metrics', 'intangibles_to_total_assets',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'stock_based_compensation_to_revenue',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'research_and_developement_to_revenue',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'sales_general_and_administrative_to_revenue',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'capex_to_revenue',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'capex_to_depreciation',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics', 'capex_to_operating_cash_flow',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'free_cash_flow_yield',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'earnings_yield',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'return_on_capital_employed',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'return_on_invested_capital',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'return_on_equity',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'return_on_tangible_assets',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'operating_return_on_assets',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'return_on_assets',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'interest_burden',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'tax_burden',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'income_quality',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('key_metrics', 'current_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics', 'net_debt_to_ebitda',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics', 'ev_to_ebitda',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics', 'ev_to_free_cash_flow',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics', 'ev_to_operating_cash_flow',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('key_metrics', 'ev_to_sales',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('institutional_ownership', 'put_call_ratio_change',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('institutional_ownership', 'last_put_call_ratio',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('institutional_ownership', 'put_call_ratio',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('institutional_ownership', 'ownership_percent_change',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('institutional_ownership', 'last_ownership_percent',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('institutional_ownership', 'ownership_percent',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('insider_statistics', 'acquired_disposed_ratio',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('income_statements', 'net_income_ratio',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('income_statements', 'income_before_tax_ratio',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('income_statements', 'operating_income_ratio',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('income_statements', 'ebitda_ratio',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('income_statements', 'gross_profit_ratio',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'enterprise_value_multiple',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'effective_tax_rate',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'debt_to_market_cap',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'price_to_fair_value',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'ebt_per_ebit',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'net_income_per_ebt',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'dividend_yield_percentage',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'dividend_yield',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'dividend_payout_ratio',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'dividend_paid_and_capex_coverage_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'capital_expenditure_coverage_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'operating_cash_flow_coverage_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'short_term_operating_cash_flow_coverage_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'interest_coverage_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'debt_service_coverage_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'free_cash_flow_operating_cash_flow_ratio',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'operating_cash_flow_sales_ratio',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'operating_cash_flow_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'working_capital_turnover_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'financial_leverage_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'long_term_debt_to_capital_ratio',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'debt_to_capital_ratio',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'debt_to_equity_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'debt_to_assets_ratio',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'price_to_operating_cash_flow_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'price_to_free_cash_flow_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'price_to_sales_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'price_to_book_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'forward_price_to_earnings_growth_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'price_to_earnings_growth_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'price_to_earnings_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'cash_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'solvency_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'quick_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'current_ratio',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'asset_turnover',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'fixed_asset_turnover',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'inventory_turnover',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'payables_turnover',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'receivables_turnover',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'bottom_line_profit_margin',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'net_profit_margin',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'continuous_operations_profit_margin',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'pretax_profit_margin',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'operating_profit_margin',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'ebitda_margin',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'ebit_margin',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('financial_ratios', 'gross_profit_margin',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('companies', 'change_percentage',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('companies', 'last_dividend',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('companies', 'beta',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('analyst_estimates', 'eps_low',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('analyst_estimates', 'eps_high',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('analyst_estimates', 'eps_avg',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
