"""add nasdaq etf screener profiles table

Revision ID: b6e077c05755
Revises: 394742ec64c0
Create Date: 2025-11-11 22:14:46.108187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e077c05755'
down_revision: Union[str, Sequence[str], None] = '394742ec64c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nasdaq_etf_screener_profiles',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('last_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('net_change', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('percent_change', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('delta', sa.String(length=10), nullable=True),
    sa.Column('one_year_percent_change', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'snapshot_date')
    )
    op.create_index(op.f('ix_nasdaq_etf_screener_profiles_symbol'), 'nasdaq_etf_screener_profiles', ['symbol'], unique=False)
    op.create_index('ix_nasdaq_etf_screener_snapshot_date', 'nasdaq_etf_screener_profiles', ['snapshot_date'], unique=False)
    op.create_index('ix_nasdaq_etf_screener_symbol_date', 'nasdaq_etf_screener_profiles', ['symbol', 'snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nasdaq_etf_screener_symbol_date', table_name='nasdaq_etf_screener_profiles')
    op.drop_index('ix_nasdaq_etf_screener_snapshot_date', table_name='nasdaq_etf_screener_profiles')
    op.drop_index(op.f('ix_nasdaq_etf_screener_profiles_symbol'), table_name='nasdaq_etf_screener_profiles')
    op.drop_table('nasdaq_etf_screener_profiles')
    # ### end Alembic commands ###
