"""Add BLS PR (Major Sector Productivity and Costs) tables

Revision ID: b91fe07325c9
Revises: 444b0ef8d83c
Create Date: 2025-11-16 07:50:30.719868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b91fe07325c9'
down_revision: Union[str, Sequence[str], None] = '444b0ef8d83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_pr_classes',
    sa.Column('class_code', sa.String(length=5), nullable=False),
    sa.Column('class_text', sa.String(length=200), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('class_code')
    )
    op.create_table('bls_pr_durations',
    sa.Column('duration_code', sa.String(length=5), nullable=False),
    sa.Column('duration_text', sa.String(length=200), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('duration_code')
    )
    op.create_table('bls_pr_measures',
    sa.Column('measure_code', sa.String(length=5), nullable=False),
    sa.Column('measure_text', sa.String(length=500), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('measure_code')
    )
    op.create_table('bls_pr_sectors',
    sa.Column('sector_code', sa.String(length=10), nullable=False),
    sa.Column('sector_name', sa.String(length=500), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sector_code')
    )
    op.create_table('bls_pr_series',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('sector_code', sa.String(length=10), nullable=True),
    sa.Column('class_code', sa.String(length=5), nullable=True),
    sa.Column('measure_code', sa.String(length=5), nullable=True),
    sa.Column('duration_code', sa.String(length=5), nullable=True),
    sa.Column('seasonal', sa.String(length=1), nullable=True),
    sa.Column('base_year', sa.String(length=10), nullable=True),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('begin_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_period', sa.String(length=5), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_period', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_code'], ['bls_pr_classes.class_code'], ),
    sa.ForeignKeyConstraint(['duration_code'], ['bls_pr_durations.duration_code'], ),
    sa.ForeignKeyConstraint(['measure_code'], ['bls_pr_measures.measure_code'], ),
    sa.ForeignKeyConstraint(['sector_code'], ['bls_pr_sectors.sector_code'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index('ix_bls_pr_series_active', 'bls_pr_series', ['is_active'], unique=False)
    op.create_index('ix_bls_pr_series_measure', 'bls_pr_series', ['measure_code'], unique=False)
    op.create_index('ix_bls_pr_series_sector', 'bls_pr_series', ['sector_code'], unique=False)
    op.create_table('bls_pr_data',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=1), nullable=True),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['bls_pr_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'year', 'period')
    )
    op.create_index('ix_bls_pr_data_series_year', 'bls_pr_data', ['series_id', 'year'], unique=False)
    op.create_index('ix_bls_pr_data_year_period', 'bls_pr_data', ['year', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bls_pr_data_year_period', table_name='bls_pr_data')
    op.drop_index('ix_bls_pr_data_series_year', table_name='bls_pr_data')
    op.drop_table('bls_pr_data')
    op.drop_index('ix_bls_pr_series_sector', table_name='bls_pr_series')
    op.drop_index('ix_bls_pr_series_measure', table_name='bls_pr_series')
    op.drop_index('ix_bls_pr_series_active', table_name='bls_pr_series')
    op.drop_table('bls_pr_series')
    op.drop_table('bls_pr_sectors')
    op.drop_table('bls_pr_measures')
    op.drop_table('bls_pr_durations')
    op.drop_table('bls_pr_classes')
    # ### end Alembic commands ###
