"""add ratios ttm bulk table

Revision ID: c5a9d36f92cd
Revises: 548089846f02
Create Date: 2025-11-13 23:35:49.726991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a9d36f92cd'
down_revision: Union[str, Sequence[str], None] = '548089846f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratios_ttm_bulk',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('gross_profit_margin_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('ebit_margin_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('ebitda_margin_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('operating_profit_margin_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('pretax_profit_margin_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('continuous_operations_profit_margin_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('net_profit_margin_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('bottom_line_profit_margin_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('receivables_turnover_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('payables_turnover_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('inventory_turnover_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('fixed_asset_turnover_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('asset_turnover_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('current_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('quick_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('solvency_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('cash_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('price_to_earnings_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('price_to_earnings_growth_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('forward_price_to_earnings_growth_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('price_to_book_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('price_to_sales_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('price_to_free_cash_flow_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('price_to_operating_cash_flow_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('debt_to_assets_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('debt_to_equity_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('debt_to_capital_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('long_term_debt_to_capital_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('financial_leverage_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('working_capital_turnover_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('operating_cash_flow_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('operating_cash_flow_sales_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('free_cash_flow_operating_cash_flow_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('debt_service_coverage_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('interest_coverage_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('short_term_operating_cash_flow_coverage_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('operating_cash_flow_coverage_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('capital_expenditure_coverage_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('dividend_paid_and_capex_coverage_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('dividend_payout_ratio_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('dividend_yield_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('enterprise_value_ttm', sa.BigInteger(), nullable=True),
    sa.Column('revenue_per_share_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('net_income_per_share_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('interest_debt_per_share_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('cash_per_share_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('book_value_per_share_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('tangible_book_value_per_share_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('shareholders_equity_per_share_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('operating_cash_flow_per_share_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('capex_per_share_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('free_cash_flow_per_share_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('dividend_per_share_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('net_income_per_ebt_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('ebt_per_ebit_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('price_to_fair_value_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('debt_to_market_cap_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('effective_tax_rate_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('enterprise_value_multiple_ttm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_ratios_ttm_bulk_symbol'), 'ratios_ttm_bulk', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratios_ttm_bulk_symbol'), table_name='ratios_ttm_bulk')
    op.drop_table('ratios_ttm_bulk')
    # ### end Alembic commands ###
