"""Add peers_bulk table

Revision ID: c7f20147e5e3
Revises: 5a60fd1812da
Create Date: 2025-11-05 21:21:42.504063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7f20147e5e3'
down_revision: Union[str, Sequence[str], None] = '5a60fd1812da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peers_bulk',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('peers_list', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index('ix_peers_bulk_symbol', 'peers_bulk', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_peers_bulk_symbol', table_name='peers_bulk')
    op.drop_table('peers_bulk')
    # ### end Alembic commands ###
