"""add_treasury_tables

Revision ID: c80ee466b77b
Revises: 104fac9c69d9
Create Date: 2025-12-03 20:58:37.109978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c80ee466b77b'
down_revision: Union[str, Sequence[str], None] = '104fac9c69d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treasury_api_usage_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('usage_hour', sa.DateTime(), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.Column('data_bytes', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('endpoint_name', sa.String(length=100), nullable=True),
    sa.Column('http_status', sa.SmallInteger(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('records_returned', sa.Integer(), nullable=True),
    sa.Column('script_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_treasury_api_usage_date_hour', 'treasury_api_usage_log', ['usage_date', 'usage_hour'], unique=False)
    op.create_index(op.f('ix_treasury_api_usage_log_endpoint_name'), 'treasury_api_usage_log', ['endpoint_name'], unique=False)
    op.create_index(op.f('ix_treasury_api_usage_log_usage_date'), 'treasury_api_usage_log', ['usage_date'], unique=False)
    op.create_index(op.f('ix_treasury_api_usage_log_usage_hour'), 'treasury_api_usage_log', ['usage_hour'], unique=False)
    op.create_table('treasury_auction_schedule',
    sa.Column('schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('security_term', sa.String(length=20), nullable=False),
    sa.Column('auction_frequency', sa.String(length=50), nullable=True),
    sa.Column('typical_auction_day', sa.String(length=50), nullable=True),
    sa.Column('typical_settlement', sa.String(length=50), nullable=True),
    sa.Column('typical_size_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('typical_size_max', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index(op.f('ix_treasury_auction_schedule_security_term'), 'treasury_auction_schedule', ['security_term'], unique=False)
    op.create_table('treasury_auctions',
    sa.Column('auction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cusip', sa.String(length=9), nullable=False),
    sa.Column('auction_date', sa.Date(), nullable=False),
    sa.Column('security_type', sa.String(length=20), nullable=False),
    sa.Column('security_term', sa.String(length=20), nullable=False),
    sa.Column('term_months', sa.SmallInteger(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('offering_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_tendered', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_accepted', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('bid_to_cover_ratio', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('competitive_tendered', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('competitive_accepted', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('non_competitive_tendered', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('non_competitive_accepted', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('primary_dealer_tendered', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('primary_dealer_accepted', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('direct_bidder_tendered', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('direct_bidder_accepted', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('indirect_bidder_accepted', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('high_yield', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('high_discount_rate', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('low_yield', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('median_yield', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('coupon_rate', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('price_per_100', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('wi_yield', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('tail_bps', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('auction_score', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('auction_result', sa.String(length=20), nullable=True),
    sa.Column('source_endpoint', sa.String(length=100), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('auction_id'),
    sa.UniqueConstraint('cusip', 'auction_date', name='uq_treasury_auction_cusip_date')
    )
    op.create_index(op.f('ix_treasury_auctions_auction_date'), 'treasury_auctions', ['auction_date'], unique=False)
    op.create_index(op.f('ix_treasury_auctions_cusip'), 'treasury_auctions', ['cusip'], unique=False)
    op.create_index('ix_treasury_auctions_date_term', 'treasury_auctions', ['auction_date', 'security_term'], unique=False)
    op.create_index('ix_treasury_auctions_result', 'treasury_auctions', ['auction_result'], unique=False)
    op.create_index(op.f('ix_treasury_auctions_security_term'), 'treasury_auctions', ['security_term'], unique=False)
    op.create_index(op.f('ix_treasury_auctions_security_type'), 'treasury_auctions', ['security_type'], unique=False)
    op.create_index('ix_treasury_auctions_term', 'treasury_auctions', ['security_term'], unique=False)
    op.create_table('treasury_collection_runs',
    sa.Column('run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_type', sa.String(length=50), nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('security_term', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('year_spec', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('api_requests_made', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_treasury_collection_runs_collection_type'), 'treasury_collection_runs', ['collection_type'], unique=False)
    op.create_index(op.f('ix_treasury_collection_runs_status'), 'treasury_collection_runs', ['status'], unique=False)
    op.create_index('ix_treasury_runs_started', 'treasury_collection_runs', ['started_at'], unique=False)
    op.create_index('ix_treasury_runs_type_status', 'treasury_collection_runs', ['collection_type', 'status'], unique=False)
    op.create_table('treasury_daily_rates',
    sa.Column('rate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('yield_1m', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('yield_3m', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('yield_6m', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('yield_1y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('yield_2y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('yield_3y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('yield_5y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('yield_7y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('yield_10y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('yield_20y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('yield_30y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('spread_2s10s', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('spread_2s30s', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('spread_5s30s', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('real_yield_5y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('real_yield_10y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('real_yield_30y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('breakeven_5y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('breakeven_10y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rate_id'),
    sa.UniqueConstraint('rate_date', name='uq_treasury_daily_rates_date')
    )
    op.create_index(op.f('ix_treasury_daily_rates_rate_date'), 'treasury_daily_rates', ['rate_date'], unique=False)
    op.create_table('treasury_data_freshness',
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('latest_data_date', sa.Date(), nullable=True),
    sa.Column('latest_auction_term', sa.String(length=20), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_update_detected', sa.DateTime(), nullable=True),
    sa.Column('needs_update', sa.Boolean(), nullable=False),
    sa.Column('update_in_progress', sa.Boolean(), nullable=False),
    sa.Column('last_update_started', sa.DateTime(), nullable=True),
    sa.Column('last_update_completed', sa.DateTime(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('total_checks', sa.Integer(), nullable=False),
    sa.Column('total_updates', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('data_type')
    )
    op.create_index(op.f('ix_treasury_data_freshness_last_checked_at'), 'treasury_data_freshness', ['last_checked_at'], unique=False)
    op.create_index(op.f('ix_treasury_data_freshness_needs_update'), 'treasury_data_freshness', ['needs_update'], unique=False)
    op.create_table('treasury_security_types',
    sa.Column('security_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('security_type')
    )
    op.create_table('treasury_upcoming_auctions',
    sa.Column('upcoming_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cusip', sa.String(length=9), nullable=True),
    sa.Column('security_type', sa.String(length=20), nullable=False),
    sa.Column('security_term', sa.String(length=20), nullable=False),
    sa.Column('auction_date', sa.Date(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('offering_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('upcoming_id')
    )
    op.create_index(op.f('ix_treasury_upcoming_auctions_auction_date'), 'treasury_upcoming_auctions', ['auction_date'], unique=False)
    op.create_index(op.f('ix_treasury_upcoming_auctions_cusip'), 'treasury_upcoming_auctions', ['cusip'], unique=False)
    op.create_index(op.f('ix_treasury_upcoming_auctions_is_processed'), 'treasury_upcoming_auctions', ['is_processed'], unique=False)
    op.create_index(op.f('ix_treasury_upcoming_auctions_security_term'), 'treasury_upcoming_auctions', ['security_term'], unique=False)
    op.create_index('ix_treasury_upcoming_date_term', 'treasury_upcoming_auctions', ['auction_date', 'security_term'], unique=False)
    op.create_table('treasury_auction_reactions',
    sa.Column('reaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('time_bucket', sa.String(length=10), nullable=False),
    sa.Column('yield_2y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('yield_5y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('yield_7y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('yield_10y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('yield_20y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('yield_30y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('delta_yield_2y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('delta_yield_5y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('delta_yield_7y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('delta_yield_10y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('delta_yield_20y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('delta_yield_30y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('spx_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('spx_return', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('nasdaq_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('nasdaq_return', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('vix_level', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('vix_change', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('mortgage_30y', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('dxy_level', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('dxy_change', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['treasury_auctions.auction_id'], ),
    sa.PrimaryKeyConstraint('reaction_id'),
    sa.UniqueConstraint('auction_id', 'time_bucket', name='uq_treasury_reaction_auction_bucket')
    )
    op.create_index(op.f('ix_treasury_auction_reactions_auction_id'), 'treasury_auction_reactions', ['auction_id'], unique=False)
    op.create_index('ix_treasury_reactions_time', 'treasury_auction_reactions', ['time_bucket'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_treasury_reactions_time', table_name='treasury_auction_reactions')
    op.drop_index(op.f('ix_treasury_auction_reactions_auction_id'), table_name='treasury_auction_reactions')
    op.drop_table('treasury_auction_reactions')
    op.drop_index('ix_treasury_upcoming_date_term', table_name='treasury_upcoming_auctions')
    op.drop_index(op.f('ix_treasury_upcoming_auctions_security_term'), table_name='treasury_upcoming_auctions')
    op.drop_index(op.f('ix_treasury_upcoming_auctions_is_processed'), table_name='treasury_upcoming_auctions')
    op.drop_index(op.f('ix_treasury_upcoming_auctions_cusip'), table_name='treasury_upcoming_auctions')
    op.drop_index(op.f('ix_treasury_upcoming_auctions_auction_date'), table_name='treasury_upcoming_auctions')
    op.drop_table('treasury_upcoming_auctions')
    op.drop_table('treasury_security_types')
    op.drop_index(op.f('ix_treasury_data_freshness_needs_update'), table_name='treasury_data_freshness')
    op.drop_index(op.f('ix_treasury_data_freshness_last_checked_at'), table_name='treasury_data_freshness')
    op.drop_table('treasury_data_freshness')
    op.drop_index(op.f('ix_treasury_daily_rates_rate_date'), table_name='treasury_daily_rates')
    op.drop_table('treasury_daily_rates')
    op.drop_index('ix_treasury_runs_type_status', table_name='treasury_collection_runs')
    op.drop_index('ix_treasury_runs_started', table_name='treasury_collection_runs')
    op.drop_index(op.f('ix_treasury_collection_runs_status'), table_name='treasury_collection_runs')
    op.drop_index(op.f('ix_treasury_collection_runs_collection_type'), table_name='treasury_collection_runs')
    op.drop_table('treasury_collection_runs')
    op.drop_index('ix_treasury_auctions_term', table_name='treasury_auctions')
    op.drop_index(op.f('ix_treasury_auctions_security_type'), table_name='treasury_auctions')
    op.drop_index(op.f('ix_treasury_auctions_security_term'), table_name='treasury_auctions')
    op.drop_index('ix_treasury_auctions_result', table_name='treasury_auctions')
    op.drop_index('ix_treasury_auctions_date_term', table_name='treasury_auctions')
    op.drop_index(op.f('ix_treasury_auctions_cusip'), table_name='treasury_auctions')
    op.drop_index(op.f('ix_treasury_auctions_auction_date'), table_name='treasury_auctions')
    op.drop_table('treasury_auctions')
    op.drop_index(op.f('ix_treasury_auction_schedule_security_term'), table_name='treasury_auction_schedule')
    op.drop_table('treasury_auction_schedule')
    op.drop_index(op.f('ix_treasury_api_usage_log_usage_hour'), table_name='treasury_api_usage_log')
    op.drop_index(op.f('ix_treasury_api_usage_log_usage_date'), table_name='treasury_api_usage_log')
    op.drop_index(op.f('ix_treasury_api_usage_log_endpoint_name'), table_name='treasury_api_usage_log')
    op.drop_index('ix_treasury_api_usage_date_hour', table_name='treasury_api_usage_log')
    op.drop_table('treasury_api_usage_log')
    # ### end Alembic commands ###
