"""Add BLS IP (Industry Productivity) tables

Revision ID: dbae27c5b3be
Revises: b91fe07325c9
Create Date: 2025-11-16 08:13:47.451943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbae27c5b3be'
down_revision: Union[str, Sequence[str], None] = 'b91fe07325c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_ip_areas',
    sa.Column('area_code', sa.String(length=10), nullable=False),
    sa.Column('area_text', sa.String(length=500), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('area_code')
    )
    op.create_table('bls_ip_durations',
    sa.Column('duration_code', sa.String(length=5), nullable=False),
    sa.Column('duration_text', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('duration_code')
    )
    op.create_table('bls_ip_industries',
    sa.Column('industry_code', sa.String(length=15), nullable=False),
    sa.Column('naics_code', sa.String(length=20), nullable=True),
    sa.Column('industry_text', sa.String(length=500), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('industry_code')
    )
    op.create_table('bls_ip_measures',
    sa.Column('measure_code', sa.String(length=5), nullable=False),
    sa.Column('measure_text', sa.String(length=500), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('measure_code')
    )
    op.create_table('bls_ip_sectors',
    sa.Column('sector_code', sa.String(length=5), nullable=False),
    sa.Column('sector_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sector_code')
    )
    op.create_table('bls_ip_types',
    sa.Column('type_code', sa.String(length=5), nullable=False),
    sa.Column('type_text', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('type_code')
    )
    op.create_table('bls_ip_series',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('seasonal', sa.String(length=1), nullable=True),
    sa.Column('sector_code', sa.String(length=5), nullable=True),
    sa.Column('industry_code', sa.String(length=15), nullable=True),
    sa.Column('measure_code', sa.String(length=5), nullable=True),
    sa.Column('duration_code', sa.String(length=5), nullable=True),
    sa.Column('base_year', sa.String(length=10), nullable=True),
    sa.Column('type_code', sa.String(length=5), nullable=True),
    sa.Column('area_code', sa.String(length=10), nullable=True),
    sa.Column('series_title', sa.Text(), nullable=True),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('begin_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_period', sa.String(length=5), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_period', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_code'], ['bls_ip_areas.area_code'], ),
    sa.ForeignKeyConstraint(['duration_code'], ['bls_ip_durations.duration_code'], ),
    sa.ForeignKeyConstraint(['industry_code'], ['bls_ip_industries.industry_code'], ),
    sa.ForeignKeyConstraint(['measure_code'], ['bls_ip_measures.measure_code'], ),
    sa.ForeignKeyConstraint(['sector_code'], ['bls_ip_sectors.sector_code'], ),
    sa.ForeignKeyConstraint(['type_code'], ['bls_ip_types.type_code'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index('ix_bls_ip_series_active', 'bls_ip_series', ['is_active'], unique=False)
    op.create_index('ix_bls_ip_series_industry', 'bls_ip_series', ['industry_code'], unique=False)
    op.create_index('ix_bls_ip_series_measure', 'bls_ip_series', ['measure_code'], unique=False)
    op.create_index('ix_bls_ip_series_sector', 'bls_ip_series', ['sector_code'], unique=False)
    op.create_table('bls_ip_data',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=3), nullable=True),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['bls_ip_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'year', 'period')
    )
    op.create_index('ix_bls_ip_data_series_year', 'bls_ip_data', ['series_id', 'year'], unique=False)
    op.create_index('ix_bls_ip_data_year_period', 'bls_ip_data', ['year', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bls_ip_data_year_period', table_name='bls_ip_data')
    op.drop_index('ix_bls_ip_data_series_year', table_name='bls_ip_data')
    op.drop_table('bls_ip_data')
    op.drop_index('ix_bls_ip_series_sector', table_name='bls_ip_series')
    op.drop_index('ix_bls_ip_series_measure', table_name='bls_ip_series')
    op.drop_index('ix_bls_ip_series_industry', table_name='bls_ip_series')
    op.drop_index('ix_bls_ip_series_active', table_name='bls_ip_series')
    op.drop_table('bls_ip_series')
    op.drop_table('bls_ip_types')
    op.drop_table('bls_ip_sectors')
    op.drop_table('bls_ip_measures')
    op.drop_table('bls_ip_industries')
    op.drop_table('bls_ip_durations')
    op.drop_table('bls_ip_areas')
    # ### end Alembic commands ###
