"""Add BLS PC (Producer Price Index - Industry) tables

Revision ID: ddc44ede0b7b
Revises: cb3dbdd11ab9
Create Date: 2025-11-15 18:03:23.405932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc44ede0b7b'
down_revision: Union[str, Sequence[str], None] = 'cb3dbdd11ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_pc_industries',
    sa.Column('industry_code', sa.String(length=10), nullable=False),
    sa.Column('industry_name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('industry_code')
    )
    op.create_table('bls_pc_products',
    sa.Column('industry_code', sa.String(length=10), nullable=False),
    sa.Column('product_code', sa.String(length=20), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['industry_code'], ['bls_pc_industries.industry_code'], ),
    sa.PrimaryKeyConstraint('industry_code', 'product_code')
    )
    op.create_table('bls_pc_series',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('industry_code', sa.String(length=10), nullable=True),
    sa.Column('product_code', sa.String(length=20), nullable=True),
    sa.Column('seasonal_code', sa.String(length=1), nullable=True),
    sa.Column('base_date', sa.String(length=10), nullable=True),
    sa.Column('series_title', sa.Text(), nullable=False),
    sa.Column('footnote_codes', sa.String(length=50), nullable=True),
    sa.Column('begin_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_period', sa.String(length=5), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_period', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['industry_code'], ['bls_pc_industries.industry_code'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index('ix_bls_pc_series_active', 'bls_pc_series', ['is_active'], unique=False)
    op.create_index('ix_bls_pc_series_industry', 'bls_pc_series', ['industry_code'], unique=False)
    op.create_index('ix_bls_pc_series_seasonal', 'bls_pc_series', ['seasonal_code'], unique=False)
    op.create_table('bls_pc_data',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=3), nullable=True),
    sa.Column('footnote_codes', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['bls_pc_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'year', 'period')
    )
    op.create_index('ix_bls_pc_data_series_year', 'bls_pc_data', ['series_id', 'year'], unique=False)
    op.create_index('ix_bls_pc_data_year_period', 'bls_pc_data', ['year', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bls_pc_data_year_period', table_name='bls_pc_data')
    op.drop_index('ix_bls_pc_data_series_year', table_name='bls_pc_data')
    op.drop_table('bls_pc_data')
    op.drop_index('ix_bls_pc_series_seasonal', table_name='bls_pc_series')
    op.drop_index('ix_bls_pc_series_industry', table_name='bls_pc_series')
    op.drop_index('ix_bls_pc_series_active', table_name='bls_pc_series')
    op.drop_table('bls_pc_series')
    op.drop_table('bls_pc_products')
    op.drop_table('bls_pc_industries')
    # ### end Alembic commands ###
