"""Add BLS SM (State and Metro Area Employment) tables

Revision ID: e64d24aefe1c
Revises: 45ee62d5af26
Create Date: 2025-11-15 23:32:29.561337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e64d24aefe1c'
down_revision: Union[str, Sequence[str], None] = '45ee62d5af26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_sm_areas',
    sa.Column('area_code', sa.String(length=10), nullable=False),
    sa.Column('area_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('area_code')
    )
    op.create_table('bls_sm_industries',
    sa.Column('industry_code', sa.String(length=10), nullable=False),
    sa.Column('industry_name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('industry_code')
    )
    op.create_table('bls_sm_states',
    sa.Column('state_code', sa.String(length=5), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state_code')
    )
    op.create_table('bls_sm_supersectors',
    sa.Column('supersector_code', sa.String(length=5), nullable=False),
    sa.Column('supersector_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('supersector_code')
    )
    op.create_table('bls_sm_series',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('state_code', sa.String(length=5), nullable=True),
    sa.Column('area_code', sa.String(length=10), nullable=True),
    sa.Column('supersector_code', sa.String(length=5), nullable=True),
    sa.Column('industry_code', sa.String(length=10), nullable=True),
    sa.Column('data_type_code', sa.String(length=5), nullable=True),
    sa.Column('seasonal_code', sa.String(length=1), nullable=True),
    sa.Column('benchmark_year', sa.SmallInteger(), nullable=True),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('begin_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_period', sa.String(length=5), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_period', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_code'], ['bls_sm_areas.area_code'], ),
    sa.ForeignKeyConstraint(['industry_code'], ['bls_sm_industries.industry_code'], ),
    sa.ForeignKeyConstraint(['state_code'], ['bls_sm_states.state_code'], ),
    sa.ForeignKeyConstraint(['supersector_code'], ['bls_sm_supersectors.supersector_code'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index('ix_bls_sm_series_active', 'bls_sm_series', ['is_active'], unique=False)
    op.create_index('ix_bls_sm_series_area', 'bls_sm_series', ['area_code'], unique=False)
    op.create_index('ix_bls_sm_series_industry', 'bls_sm_series', ['industry_code'], unique=False)
    op.create_index('ix_bls_sm_series_seasonal', 'bls_sm_series', ['seasonal_code'], unique=False)
    op.create_index('ix_bls_sm_series_state', 'bls_sm_series', ['state_code'], unique=False)
    op.create_table('bls_sm_data',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=1), nullable=True),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['bls_sm_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'year', 'period')
    )
    op.create_index('ix_bls_sm_data_series_year', 'bls_sm_data', ['series_id', 'year'], unique=False)
    op.create_index('ix_bls_sm_data_year_period', 'bls_sm_data', ['year', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bls_sm_data_year_period', table_name='bls_sm_data')
    op.drop_index('ix_bls_sm_data_series_year', table_name='bls_sm_data')
    op.drop_table('bls_sm_data')
    op.drop_index('ix_bls_sm_series_state', table_name='bls_sm_series')
    op.drop_index('ix_bls_sm_series_seasonal', table_name='bls_sm_series')
    op.drop_index('ix_bls_sm_series_industry', table_name='bls_sm_series')
    op.drop_index('ix_bls_sm_series_area', table_name='bls_sm_series')
    op.drop_index('ix_bls_sm_series_active', table_name='bls_sm_series')
    op.drop_table('bls_sm_series')
    op.drop_table('bls_sm_supersectors')
    op.drop_table('bls_sm_states')
    op.drop_table('bls_sm_industries')
    op.drop_table('bls_sm_areas')
    # ### end Alembic commands ###
