"""Add BLS LA (Local Area Unemployment) tables

Revision ID: eba7d020c96d
Revises: eba9ea2d9c5e
Create Date: 2025-11-15 14:45:40.763222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba7d020c96d'
down_revision: Union[str, Sequence[str], None] = 'eba9ea2d9c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_la_measures',
    sa.Column('measure_code', sa.String(length=5), nullable=False),
    sa.Column('measure_text', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('measure_code')
    )
    op.create_table('bls_la_series',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('area_type_code', sa.String(length=1), nullable=True),
    sa.Column('area_code', sa.String(length=20), nullable=True),
    sa.Column('measure_code', sa.String(length=5), nullable=True),
    sa.Column('seasonal_code', sa.String(length=1), nullable=True),
    sa.Column('srd_code', sa.String(length=5), nullable=True),
    sa.Column('series_title', sa.Text(), nullable=False),
    sa.Column('footnote_codes', sa.String(length=50), nullable=True),
    sa.Column('begin_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_period', sa.String(length=5), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_period', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_code'], ['bls_areas.area_code'], ),
    sa.ForeignKeyConstraint(['measure_code'], ['bls_la_measures.measure_code'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index('ix_bls_la_series_active', 'bls_la_series', ['is_active'], unique=False)
    op.create_index('ix_bls_la_series_area', 'bls_la_series', ['area_code'], unique=False)
    op.create_index('ix_bls_la_series_area_type', 'bls_la_series', ['area_type_code'], unique=False)
    op.create_index('ix_bls_la_series_measure', 'bls_la_series', ['measure_code'], unique=False)
    op.create_index('ix_bls_la_series_seasonal', 'bls_la_series', ['seasonal_code'], unique=False)
    op.create_table('bls_la_data',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=1), nullable=True),
    sa.Column('footnote_codes', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['bls_la_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'year', 'period')
    )
    op.create_index('ix_bls_la_data_series_year', 'bls_la_data', ['series_id', 'year'], unique=False)
    op.create_index('ix_bls_la_data_year_period', 'bls_la_data', ['year', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bls_la_data_year_period', table_name='bls_la_data')
    op.drop_index('ix_bls_la_data_series_year', table_name='bls_la_data')
    op.drop_table('bls_la_data')
    op.drop_index('ix_bls_la_series_seasonal', table_name='bls_la_series')
    op.drop_index('ix_bls_la_series_measure', table_name='bls_la_series')
    op.drop_index('ix_bls_la_series_area_type', table_name='bls_la_series')
    op.drop_index('ix_bls_la_series_area', table_name='bls_la_series')
    op.drop_index('ix_bls_la_series_active', table_name='bls_la_series')
    op.drop_table('bls_la_series')
    op.drop_table('bls_la_measures')
    # ### end Alembic commands ###
