"""Add BLS CU (CPI) tables

Revision ID: eba9ea2d9c5e
Revises: 4770a74e36cc
Create Date: 2025-11-15 13:32:45.766333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba9ea2d9c5e'
down_revision: Union[str, Sequence[str], None] = '4770a74e36cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_cu_items',
    sa.Column('item_code', sa.String(length=20), nullable=False),
    sa.Column('item_name', sa.String(length=500), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('item_code')
    )
    op.create_index('ix_bls_cu_items_display_level', 'bls_cu_items', ['display_level'], unique=False)
    op.create_index('ix_bls_cu_items_selectable', 'bls_cu_items', ['selectable'], unique=False)
    op.create_table('bls_periodicity',
    sa.Column('periodicity_code', sa.String(length=5), nullable=False),
    sa.Column('periodicity_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('periodicity_code')
    )
    op.create_table('bls_cu_series',
    sa.Column('series_id', sa.String(length=20), nullable=False),
    sa.Column('area_code', sa.String(length=10), nullable=True),
    sa.Column('item_code', sa.String(length=20), nullable=True),
    sa.Column('seasonal_code', sa.String(length=1), nullable=True),
    sa.Column('periodicity_code', sa.String(length=5), nullable=True),
    sa.Column('base_code', sa.String(length=10), nullable=True),
    sa.Column('base_period', sa.String(length=50), nullable=True),
    sa.Column('series_title', sa.Text(), nullable=False),
    sa.Column('footnote_codes', sa.String(length=50), nullable=True),
    sa.Column('begin_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_period', sa.String(length=5), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_period', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_code'], ['bls_areas.area_code'], ),
    sa.ForeignKeyConstraint(['item_code'], ['bls_cu_items.item_code'], ),
    sa.ForeignKeyConstraint(['periodicity_code'], ['bls_periodicity.periodicity_code'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index('ix_bls_cu_series_active', 'bls_cu_series', ['is_active'], unique=False)
    op.create_index('ix_bls_cu_series_area', 'bls_cu_series', ['area_code'], unique=False)
    op.create_index('ix_bls_cu_series_item', 'bls_cu_series', ['item_code'], unique=False)
    op.create_index('ix_bls_cu_series_seasonal', 'bls_cu_series', ['seasonal_code'], unique=False)
    op.create_table('bls_cu_aspects',
    sa.Column('series_id', sa.String(length=20), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('aspect_type', sa.String(length=5), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('footnote_codes', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['bls_cu_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'year', 'period', 'aspect_type')
    )
    op.create_index('ix_bls_cu_aspects_series_year', 'bls_cu_aspects', ['series_id', 'year'], unique=False)
    op.create_index('ix_bls_cu_aspects_type', 'bls_cu_aspects', ['aspect_type'], unique=False)
    op.create_table('bls_cu_data',
    sa.Column('series_id', sa.String(length=20), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('footnote_codes', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['bls_cu_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'year', 'period')
    )
    op.create_index('ix_bls_cu_data_series_year', 'bls_cu_data', ['series_id', 'year'], unique=False)
    op.create_index('ix_bls_cu_data_year_period', 'bls_cu_data', ['year', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bls_cu_data_year_period', table_name='bls_cu_data')
    op.drop_index('ix_bls_cu_data_series_year', table_name='bls_cu_data')
    op.drop_table('bls_cu_data')
    op.drop_index('ix_bls_cu_aspects_type', table_name='bls_cu_aspects')
    op.drop_index('ix_bls_cu_aspects_series_year', table_name='bls_cu_aspects')
    op.drop_table('bls_cu_aspects')
    op.drop_index('ix_bls_cu_series_seasonal', table_name='bls_cu_series')
    op.drop_index('ix_bls_cu_series_item', table_name='bls_cu_series')
    op.drop_index('ix_bls_cu_series_area', table_name='bls_cu_series')
    op.drop_index('ix_bls_cu_series_active', table_name='bls_cu_series')
    op.drop_table('bls_cu_series')
    op.drop_table('bls_periodicity')
    op.drop_index('ix_bls_cu_items_selectable', table_name='bls_cu_items')
    op.drop_index('ix_bls_cu_items_display_level', table_name='bls_cu_items')
    op.drop_table('bls_cu_items')
    # ### end Alembic commands ###
