"""add bls_la_areas table and update la series foreign key

Revision ID: ed546fe6ba3a
Revises: 85443bfe6cec
Create Date: 2025-11-16 22:04:05.127563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed546fe6ba3a'
down_revision: Union[str, Sequence[str], None] = '85443bfe6cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_la_areas',
    sa.Column('area_code', sa.String(length=20), nullable=False),
    sa.Column('area_type_code', sa.String(length=1), nullable=True),
    sa.Column('area_text', sa.String(length=255), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('area_code')
    )
    op.create_index('ix_bls_la_areas_display_level', 'bls_la_areas', ['display_level'], unique=False)
    op.create_index('ix_bls_la_areas_selectable', 'bls_la_areas', ['selectable'], unique=False)
    op.create_index('ix_bls_la_areas_type', 'bls_la_areas', ['area_type_code'], unique=False)

    # Copy existing area data from bls_areas for LA area codes to maintain referential integrity
    # This ensures FK constraint can be added without errors
    # Note: area_text will use area_name from bls_areas temporarily, will be overwritten when la.area is loaded
    op.execute("""
        INSERT INTO bls_la_areas (area_code, area_type_code, area_text, display_level, selectable, sort_sequence, created_at, updated_at)
        SELECT DISTINCT
            s.area_code,
            s.area_type_code,
            COALESCE(a.area_name, 'Unknown Area') as area_text,
            0 as display_level,
            'T' as selectable,
            0 as sort_sequence,
            NOW() as created_at,
            NOW() as updated_at
        FROM bls_la_series s
        LEFT JOIN bls_areas a ON s.area_code = a.area_code
        ON CONFLICT (area_code) DO NOTHING
    """)

    op.drop_constraint(op.f('bls_la_series_area_code_fkey'), 'bls_la_series', type_='foreignkey')
    op.create_foreign_key(None, 'bls_la_series', 'bls_la_areas', ['area_code'], ['area_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bls_la_series', type_='foreignkey')
    op.create_foreign_key(op.f('bls_la_series_area_code_fkey'), 'bls_la_series', 'bls_areas', ['area_code'], ['area_code'])
    op.drop_index('ix_bls_la_areas_type', table_name='bls_la_areas')
    op.drop_index('ix_bls_la_areas_selectable', table_name='bls_la_areas')
    op.drop_index('ix_bls_la_areas_display_level', table_name='bls_la_areas')
    op.drop_table('bls_la_areas')
    # ### end Alembic commands ###
