"""Add BLS JT (JOLTS - Job Openings and Labor Turnover) tables

Revision ID: efeaf077ec52
Revises: e64d24aefe1c
Create Date: 2025-11-16 01:03:18.112629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efeaf077ec52'
down_revision: Union[str, Sequence[str], None] = 'e64d24aefe1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_jt_areas',
    sa.Column('area_code', sa.String(length=10), nullable=False),
    sa.Column('area_text', sa.String(length=200), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('area_code')
    )
    op.create_table('bls_jt_dataelements',
    sa.Column('dataelement_code', sa.String(length=5), nullable=False),
    sa.Column('dataelement_text', sa.String(length=200), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('dataelement_code')
    )
    op.create_table('bls_jt_industries',
    sa.Column('industry_code', sa.String(length=10), nullable=False),
    sa.Column('industry_text', sa.String(length=500), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('industry_code')
    )
    op.create_table('bls_jt_ratelevels',
    sa.Column('ratelevel_code', sa.String(length=1), nullable=False),
    sa.Column('ratelevel_text', sa.String(length=200), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ratelevel_code')
    )
    op.create_table('bls_jt_sizeclasses',
    sa.Column('sizeclass_code', sa.String(length=5), nullable=False),
    sa.Column('sizeclass_text', sa.String(length=200), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sizeclass_code')
    )
    op.create_table('bls_jt_states',
    sa.Column('state_code', sa.String(length=5), nullable=False),
    sa.Column('state_text', sa.String(length=200), nullable=False),
    sa.Column('display_level', sa.SmallInteger(), nullable=True),
    sa.Column('selectable', sa.String(length=1), nullable=True),
    sa.Column('sort_sequence', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state_code')
    )
    op.create_table('bls_jt_series',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('seasonal', sa.String(length=1), nullable=True),
    sa.Column('industry_code', sa.String(length=10), nullable=True),
    sa.Column('state_code', sa.String(length=5), nullable=True),
    sa.Column('area_code', sa.String(length=10), nullable=True),
    sa.Column('sizeclass_code', sa.String(length=5), nullable=True),
    sa.Column('dataelement_code', sa.String(length=5), nullable=True),
    sa.Column('ratelevel_code', sa.String(length=1), nullable=True),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('begin_year', sa.SmallInteger(), nullable=True),
    sa.Column('begin_period', sa.String(length=5), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_period', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_code'], ['bls_jt_areas.area_code'], ),
    sa.ForeignKeyConstraint(['dataelement_code'], ['bls_jt_dataelements.dataelement_code'], ),
    sa.ForeignKeyConstraint(['industry_code'], ['bls_jt_industries.industry_code'], ),
    sa.ForeignKeyConstraint(['ratelevel_code'], ['bls_jt_ratelevels.ratelevel_code'], ),
    sa.ForeignKeyConstraint(['sizeclass_code'], ['bls_jt_sizeclasses.sizeclass_code'], ),
    sa.ForeignKeyConstraint(['state_code'], ['bls_jt_states.state_code'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index('ix_bls_jt_series_active', 'bls_jt_series', ['is_active'], unique=False)
    op.create_index('ix_bls_jt_series_dataelement', 'bls_jt_series', ['dataelement_code'], unique=False)
    op.create_index('ix_bls_jt_series_industry', 'bls_jt_series', ['industry_code'], unique=False)
    op.create_index('ix_bls_jt_series_seasonal', 'bls_jt_series', ['seasonal'], unique=False)
    op.create_index('ix_bls_jt_series_state', 'bls_jt_series', ['state_code'], unique=False)
    op.create_table('bls_jt_data',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=1), nullable=True),
    sa.Column('footnote_codes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['bls_jt_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'year', 'period')
    )
    op.create_index('ix_bls_jt_data_series_year', 'bls_jt_data', ['series_id', 'year'], unique=False)
    op.create_index('ix_bls_jt_data_year_period', 'bls_jt_data', ['year', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bls_jt_data_year_period', table_name='bls_jt_data')
    op.drop_index('ix_bls_jt_data_series_year', table_name='bls_jt_data')
    op.drop_table('bls_jt_data')
    op.drop_index('ix_bls_jt_series_state', table_name='bls_jt_series')
    op.drop_index('ix_bls_jt_series_seasonal', table_name='bls_jt_series')
    op.drop_index('ix_bls_jt_series_industry', table_name='bls_jt_series')
    op.drop_index('ix_bls_jt_series_dataelement', table_name='bls_jt_series')
    op.drop_index('ix_bls_jt_series_active', table_name='bls_jt_series')
    op.drop_table('bls_jt_series')
    op.drop_table('bls_jt_states')
    op.drop_table('bls_jt_sizeclasses')
    op.drop_table('bls_jt_ratelevels')
    op.drop_table('bls_jt_industries')
    op.drop_table('bls_jt_dataelements')
    op.drop_table('bls_jt_areas')
    # ### end Alembic commands ###
